### ISSUE TITLE
Desenhar fluxo de trabalho da comunicação

### ISSUE THREAD

**Issue by Clarisse1983** [EscolaDeSaudePublica/FeliciLab#10]
- Como uma demanda entra no processo de trabalho da comunicação?
- Como a gente refina?
- Quem assina?

**Comment by saracafe** [comment]
Nós desmembramos essa tarefa em dois novos cards, sendo 1 criar publicação de como entrar em contato com o Publicilab e 2 inserir no onborading orientações sobre fluxos de trabalho dos labs e produtos.

**Comment by danielgula** [comment]
Este fluxo será revisto dentro do GT de Comunicação da ESP.
