### ISSUE TITLE
[17/05] Criar publicação sobre o Dia Internacional da Comunicação e das Telecomunicações

### ISSUE THREAD

**Issue by saracafe** [EscolaDeSaudePublica/FeliciLab#100]
## **Objetivo**

**Como** público interno felicilab e externo
**Quero** saber a importância da comunicação como um direito humano  
**Para** me manter informado e saber dos meus direitos

## **Contexto**

- Dia 17/05 é o Dia Internacional da Comunicação e das Telecomunicações queremos abordar a comunicação como um direito humano essencial que está na Constituição e na Unesco. E como isso se relaciona com as atividades do Felicilab. 

## **PubliciLab**

- [x] Pesquisar sobre o assunto e criar o conteúdo

## **DesignLab**

- [x] Criar a arte para instagram

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [ ] Visualizar conteúdo sobre efeméride  
**Dado que** sou uma usuária de redes sociais 
**Quando** visito o instagram do felicilab  
**então** eu visualizo e interajo com a publicação

## Observações
Links de apoio e informações adicionais

**Comment by danielgula** [comment]
![comunicar-direito-humano](https://user-images.githubusercontent.com/39468037/118538282-5c4a2200-b724-11eb-9611-3a8a1e7f79b9.jpg)
Segue versão final
