### ISSUE TITLE
[25/05] Criar publicação sobre o Dia do Orgulho Geek

### ISSUE THREAD

**Issue by saracafe** [EscolaDeSaudePublica/FeliciLab#113]
## **Objetivo**

**Como** interno e externo das redes sociais 
**Quero** comemorar o Dia do Orgulho Geek   
**Para** homenagear os nerds felicilabers e público externo

## **Contexto**

Nesta terça-feira, 25/05 é comemorado o Dia do Orgulho Geek, é uma iniciativa que defende o direito de toda pessoa gostar de quadrinhos, filmes, games, tecnologia e outros assuntos relacionados à cultura pop. A data também representa o Dia da Toalha em homenagem a Douglas Adams, autor da série O Guia do Mochileiro das Galáxias. A sua obra sempre foi um dos cânones da literatura nerd, principalmente ao misturar ficção científica com elementos humorísticos. Queremos fazer uma homenagem de forma engraçada aos nerds felicilabers e também para o público externo das redes sociais se sentirem representados. 

## **PubliciLab**

- [x] Pesquisar sobre o tema
- [x] Exercitar o poder de síntese e fazer uma legenda 
- [ ] Revisar o texto

## **DesignLab**

- [x] Pesquisar referências de artes sobre o Dia do Orgulho Geek
- [x] Montar a arte
- [x] Entregar até terça feira (25/05) de manhã 

## **Critérios de Aceitação**

- [ ] Visualizar conteúdo da publicação 
**Dado que** sou uma usuária da internet 
**Quando** visito o instagram do felicilab   
**então** eu visualizo e interajo com a publicação

## Observações
Links de apoio e informações adicionais

**Comment by danielgula** [comment]
![image](https://user-images.githubusercontent.com/39468037/119504891-ca08d600-bd42-11eb-8d9b-6a14cf950c44.png)
Para aprovação

**Comment by saracafe** [comment]
Aqui o texto: https://docs.google.com/document/d/1GbvvXMXJIZ4JZSK40t6skFEp9ewoeBVqVxLLUNFJlQI/edit?usp=sharing
