### ISSUE TITLE
[01/06] Criar publicação TV na palma da mão

### ISSUE THREAD

**Issue by saracafe** [EscolaDeSaudePublica/FeliciLab#116]
## **Objetivo**

**Como** público externo as redes sociais  
**Quero** falar sobre evolução da TV  
**Para** informar o leitor 

## **Contexto**

A primeira transmissão de TV no Brasil ocorreu no dia 1º de junho de 1950. No post, vamos dar ênfase a evolução na transmissão de imagens, falar sobre as smarts tvs com conexão e a internet das coisas. 

## **PubliciLab**

- [x] Pesquisar sobre o tema
- [x]  Exercitar o poder de síntese e fazer uma legenda
- [x] Revisar o texto

## **DesignLab**

- [x] Pesquisar referências de artes sobre tv, internet das coisas
- [x] Montar uma arte
- [x] Entregar até segunda feira (31/05)

## **Critérios de Aceitação**

- [x] Visualizar conteúdo da publicação
**Dado que** sou uma usuária da internet  
**Quando** visito o instagram do felicilab
**então** eu visualizo e interajo com a publicação

## Observações
Links de apoio e informações adicionais

**Comment by pauloamoreira** [comment]
.segue proposta de arte, para aprovação:
![TV_naPalmaDaMao](https://user-images.githubusercontent.com/79201419/119700241-57265a80-be29-11eb-8e4a-3fb32266dc11.png)

**Comment by Clarisse1983** [comment]
Nossa, maravilhoso, @pauloamoreira. Uma sugestão: dá pra variar a cor desse fundo? Nossas últimas postagens estão priorizando o roxo, e nossa paleta é tão diversa, né?

**Comment by pauloamoreira** [comment]
@Clarisse1983 segue nova versão, para aprovação:
![TV_naPalma_2](https://user-images.githubusercontent.com/79201419/120028681-61805a00-bfcb-11eb-8cc5-4987c0ab508e.png)

**Comment by Clarisse1983** [comment]
@pauloamoreira show! Aprovada!

**Comment by saracafe** [comment]
Aqui o texto https://docs.google.com/document/d/1mP9YGX30pRS0XX6mLSEAhPLMrHFlpzkil4ofogdbt70/edit?usp=sharing

**Comment by Clarisse1983** [comment]
Texto revisado, @saracafe <3
