### ISSUE TITLE
[05/06] Criar publicação sobre o Dia Mundial do Meio Ambiente

### ISSUE THREAD

**Issue by saracafe** [EscolaDeSaudePublica/FeliciLab#118]
## **Objetivo**

**Como** público externo das redes sociais 
**Quero** homenagear o Dia Mundial do Meio Ambiente 
**Para** refletir sobre a descarte dos resíduos

## **Contexto**

05/06 é comemorado o Dia Mundial do Meio Ambiente. Vamos destaque no post sobre como descartar as máscaras cirúrgicas adequadamente e como cuidar da PFF2 reutilizável. 

## **PubliciLab**

- [x] Pesquisar sobre o tema
- [x] Exercitar o poder de síntese e fazer uma legenda
- [x] Revisar o texto
- [x] Agendar a publicação no mlabs para sábado

## **DesignLab**

- [x] Pesquisar referências de artes sobre o Dia Mundial do Meio Ambiente, proteção e máscaras contra a covid
- [x]  Montar uma arte
- [x] Entregar até sexta feira (04/06)

## **Critérios de Aceitação**

- [x] Visualizar conteúdo da publicação  
**Dado que** sou uma usuária da internet
**Quando** visito o instagram do felicilab
**então** visito o instagram do felicilab

## Observações
Links de apoio e informações adicionais

**Comment by pauloamoreira** [comment]
@saracafe segue arte para aprovação. Este material já foi disponibilizado na pasta do Drive do PubliciLab
![DIA_DO_MEIO_AMBIENTE](https://user-images.githubusercontent.com/79201419/120726612-df9e9e00-c4ae-11eb-842e-8493cdff5773.png)

**Comment by saracafe** [comment]
@pauloamoreira gostei demais da arte :)

**Comment by saracafe** [comment]
Aqui o texto de legenda https://docs.google.com/document/d/1j37GPzV1l7RNBmzW_p6lsNnm18sF_DEyEFdyV7yyw5o/edit?usp=sharing

**Comment by Clarisse1983** [comment]
@pauloamoreira que coisa mais linda essa arte! Podia ser um adesivo!! Aprovadíssima

**Comment by Clarisse1983** [comment]
Gente, essa arte está um escândalo, digna de um adesivo para a feliciloja. Mas eu fui checar essa orientação de usar dois sacos para descartar e não encontrei nem no site da OMS. Pela checagem percebi que não há consenso. Há as fontes que recomendam o excesso de zelo, como o uso de duas sacolas com indicação escrita de que ali tem uma máscara usada, e há as fontes que recomendam apenas descarte em lixo comum. Como é uma publicação sobre o dia do meio ambiente, penso que podemos optar pelo bom senso e seguir as fontes (acredito que confiáveis) de descarte com um saquinho de plástico ou papel apenas, e no lixo comum não reciclável, como já está na arte. Acho que dica 'como o lixo do banheiro' é legal, se couber. Vc faz essa alteração, @pauloamoreira?

**Comment by pauloamoreira** [comment]
.segue nova arte, com alteração solicitada (vou atualizar o arquivo no Drive):
![DIA_DO_MEIO_AMBIENTE_ok3](https://user-images.githubusercontent.com/79201419/120822935-4498d900-c52d-11eb-85b9-d590c3c50ba7.png)
