### ISSUE TITLE
[10/06/21] Produzir material de divulgação para a Oficina de Latex

### ISSUE THREAD

**Issue by Clarisse1983** [EscolaDeSaudePublica/FeliciLab#123]
## **Objetivo**

**Como** pessoa interessada em produção de conteúdos textuais  
**Quero** participar da oficina de Latex  
**Para** aprender sobre como otimizar minha produção com uso da ferramenta

## **Contexto**

- Camila Colares vai conduzir uma oficina de de Latex e pediu nosso apoio na organização e divulgação da mesma. A oficina será realizada no nosso canal no YouTube, no dia 24/06 (ê São João), e aberta a todos os interessados. Ela explicou que vai ser bem prática, onde ela vai apresentar a ferramenta já fazendo sua utilização. Precisamos então de alguns itens que vão dar subsídio ao apoio que ela precisa no momento.

## **PubliciLab**

- [x] Conversar com Camila sobre o evento
- [x] Criar conteúdos para Instagram e canais de mensagens
- [x] Fazer a divulgação antes

## **DesignLab**

- [x] Criar card para Instagram e para canais de mensagens
- [x] Criar banner e miniatura para YouTube 

## **Critérios de Aceitação**

- [x] Ser oportunizado de participar da Oficina de Latex  
**Dado que** sou pessoa interessada no tema da Oficina
**Quando** recebo os materiais de divulgação  
**Então** posso me programar e participar do evento

## Observações
Briefing da Oficina:
https://docs.google.com/document/d/1mVrJPp9k2FQmp4i9rMP-gVjHdHb96kmPZkaWNX3pjbc/edit

**Comment by pauloamoreira** [comment]
@Clarisse1983 e @saracafe segue artes para aprovação - 1) para instagram, 2) thumbnail para youtube e 3) imagem de capa para youtube (estes arquivos foram disponibilizados no Drive do PubliciLab):
![oficina_de_LaTeX_quadrada_instagram](https://user-images.githubusercontent.com/79201419/121386945-a89e1180-c920-11eb-9746-24afc9294fe3.png)
![Oficina_de_LaTex_thumbnailYouTube_ok](https://user-images.githubusercontent.com/79201419/121386995-b2c01000-c920-11eb-9271-7766527c340d.png)
![oficina_de_LaTeX_capa_youtube1](https://user-images.githubusercontent.com/79201419/121387036-bb184b00-c920-11eb-8992-40a0d07b9e9b.png)

**Comment by pauloamoreira** [comment]
@Clarisse1983 e @saracafe segue material criado, com aperfeiçoamentos (o material no drive será substituído por esse):
![oficina_de_LaTeX_quadrada_instagram_v2](https://user-images.githubusercontent.com/79201419/121531272-a4cbc700-c9d4-11eb-960d-5971084b44fd.png)
![Oficina_de_LaTex_thumbnailYouTube-v2](https://user-images.githubusercontent.com/79201419/121531306-abf2d500-c9d4-11eb-9a27-3b7b0bdb996a.png)
![capa_youtube_v2](https://user-images.githubusercontent.com/79201419/121531323-b01ef280-c9d4-11eb-8b6e-0d6a4a79a9d2.png)
![capa_youtube2-v2](https://user-images.githubusercontent.com/79201419/121531340-b319e300-c9d4-11eb-84b3-551a5969cf39.png)

**Comment by Clarisse1983** [comment]
@pauloamoreira massa! Aprovado!

**Comment by saracafe** [comment]
@pauloamoreira precisamos modificar a arte. Agora o endereço será ESP CE no youtube

**Comment by saracafe** [comment]
@pauloamoreira precisamos de algumas modificações na arte de divulgação da Oficina de LaTex

- para o instagram: o endereço será Canal Esp Ceará no YouTube

- banner do Youtube: Júlio (da Ascom) pediu para fazer uma adaptação do thumb, medidas 1280x720px (o mesmo tamanho de arte do instagram) contendo só o título, a foto da Camila e a ilustração (ou seja, retirar as informações de ONDE e PÚBLICO)

**Comment by pauloamoreira** [comment]
@Clarisse1983 e @saracafe segue arte para substituir quadrada para Instagram/Telegram com novo endereço, bem como o novo layout medindo 1280x720 px (arquivos estarão na pasta do PubliciLab no Drive):
![oficina_de_LaTeX_quadrada_instagram_3](https://user-images.githubusercontent.com/79201419/122806090-4938ed80-d2a0-11eb-9e07-b6196d7a0554.png)
![OficinaLaTeX-thumbnail1280_720](https://user-images.githubusercontent.com/79201419/122806123-53f38280-d2a0-11eb-827f-ffe1e6b86ccd.png)

**Comment by saracafe** [comment]
Já temos o link da transmissão: https://youtu.be/o-ojTwsXMBwhttps://youtu.be/o-ojTwsXMBw

**Comment by pauloamoreira** [comment]
@Clarisse1983 e @saracafe segue arte quadrada para Instagram/Telegram com endereço da transmissão, para substituir o arquivo anterior (vou fazer a troca no drive):
![oficina_de_LaTeX_quadrada_instagram_4](https://user-images.githubusercontent.com/79201419/122969679-4ce17880-d363-11eb-807d-4459f33135d2.png)

**Comment by saracafe** [comment]
Já ia te pedir @pauloamoreira uma atualização para ascom hehehe

**Comment by saracafe** [comment]
Nessa arte do instagram/telegram precisa

- colocar o novo endereço de transmissão: https://youtu.be/o-ojTwsXMBwhttps://youtu.be/o-ojTwsXMBw
- tirar a informação do PÚBLICO

**Comment by pauloamoreira** [comment]
.ok, segue:
![oficina_de_LaTeX_quadrada_instagram_5](https://user-images.githubusercontent.com/79201419/122971244-376d4e00-d365-11eb-8dde-f4d273d59e89.png)
