### ISSUE TITLE
[28/05/21] Criar imagens iSUS para capítulo do livro

### ISSUE THREAD

**Issue by Clarisse1983** [EscolaDeSaudePublica/FeliciLab#124]
## **Objetivo**

**Como** leitor do livro com experiências da ESP de enfrentamento da pandemia
**Quero** ver imagens do iSUS no capítulo do livro 
**Para** conhecer melhor o app a partir das imagens das telas

## **Contexto**

- Estamos trabalhando no capítulo para o livro sobre o enfrentamento da pandemia, que a ESP vai publicar. Vamos falar sobre o iSUS, experiência e legado. Toda a organização está sendo conduzida e organizada pelo CiênciaLab. Possível acompanhar no [card no trello](https://trello.com/c/UZmbdYMG/28-cap%C3%ADtulo-do-livro-enfrentamento-da-covid-19-no-cear%C3%A1-como-realmente-aconteceu)

## **DesignLab**

- [x] Criar mockup de três telas do iSUS no smartphone para ilustrar o conteúdo textual: home, manejo e fale conosco. Os materiais estão nessa pasta: https://drive.google.com/drive/u/0/folders/1TWmN_iC5cqVFTQTT4LV4af43WA8pRfH8

## **Critérios de Aceitação**

- [ ] Disponibilizar imagens do iSUS para leitores do capítulo 
**Dado que** sou um leitor do capítulo sobre o iSUS no livro da ESP 
**Quando** estou nas páginas referentes ao capítulo
**Então** visualizo imagens das telas atuais do app

## Observações
Links de apoio e informações adicionais

**Comment by Clarisse1983** [comment]
@RaniGub aqui o card para registro da demanda ;)

**Comment by RaniGub** [comment]
Mockups criados. Títulos com 'no_back' são PNGs sem fundo para eventual uso. Títulos com 'print' são arquivos convertidos para impressão. Os Mockups também foram disponibilizados de forma separada para mais possibilidades de diagramação no livro.
https://drive.google.com/drive/folders/15E6br5icbAhPc9w4b80lBVpyi4dAl9HO?usp=sharing

**Comment by Clarisse1983** [comment]
@RaniGub, super ok, aprovados. Muito grata.
