### ISSUE TITLE
Criar página de links no blog

### ISSUE THREAD

**Issue by saracafe** [EscolaDeSaudePublica/FeliciLab#126]
## **Objetivo**

**Como** pessoa usuária do instagram do FeliciLab  
**Quero** acessar uma seção de links na bio  
**Para** conhecer os conteúdos disponibilizados no site

## **Contexto**

- Como estamos fomentando a produção de conteúdos nas plataformas, é necessário integrar a experiência das usuárias, e possibilitar que os conteúdos mais robustos sejam acessados no instagram a partir da disponibilização dos links do site em uma seção. Assim, resolvemos criar uma página no blog que sirva para esse propósito.

## **PubliciLab**

- [x] Criar um documento com os links que desejamos que sejam disponibilizados

## **DesignLab**

- [x] Criar a página onde serão dispostos esses links no site
- [x] Melhorar experiência mobile
- [x] Realizar treinamento com Publicilab sobre como adicionar botões

## **Critérios de Aceitação**

- [x] Criar seção de links para instagram 
**Dado que** estou no perfil do FeliciLab no instagram 
**Quando** clico no link na bio 
**Então** sou direcionada para uma seção de links importantes 

## Observações
Links de apoio e informações adicionais

Pensamos inicialmente em fazer um conta no linktree, ferramenta que permite ao usuário divulgar os links de todas as suas redes sociais na bio do instagram.  É simples e rápido no site https://linktr.ee/

**Comment by saracafe** [comment]
Links para o blog: https://docs.google.com/document/d/1toZWkBROg9as5EX49YzbJ1uO8AOdziBom1AEZN6dUN4/edit?usp=sharing

**Comment by danielgula** [comment]
Segue versão preliminar para testes e feedback:

https://sus.ce.gov.br/felicilab/links/

**Comment by saracafe** [comment]
@danielgula eu gostei, a proposta fiquei bem parecido mesmo com o linktree. Mas uma ideia para ficar uma melhor visualização: o Fala, meu povo! vai ser mensal, em vez de ter link de cada edição, podia fazer uma caixa "Fala, meu povo" e quando a pessoa clicasse lá no botão aparecesse todas as edições do informativo. No caso, Mulheres na TI, que vão ser 6 edições, a mesma coisa. Colocasse somente uma caixa Especial Mulheres na TI, e quando clicasse no botão aparecesse todas as edições.

Não sei se deu para entender hehehe mais é isso

**Comment by danielgula** [comment]
Sim podemos fazer dessa forma. Fazendo pequenos ajustes nos conteúdos geramos esse link único com agrupamento de assuntos.

**Comment by Clarisse1983** [comment]
@danielgula concordo com a Sara. Também gostei e também acho que os conteúdos que são épicos, ou seções (como o Fala, meu povo), podem ficar com um só botão. Vai ficar fofo!

**Comment by danielgula** [comment]
A página já está pronta e foi configurada para a demanda. Criei uma tarefa no card para realizar um treinamento e mostrar como criamos os botões. Só agendar! 30min resolvemos.

**Comment by danielgula** [comment]
Página ajustada de acordo com nosso refinamento e aguardando aprovação e agendamento do treinamento:
- ajuste de tons
- padronagem dos favicons
- remoção do menu superior
- inclusão de links de redes separados
https://sus.ce.gov.br/felicilab/links/

**Comment by Clarisse1983** [comment]
Mas já vamos usar no insta, já coloquei lá! ;)

**Comment by danielgula** [comment]
> @danielgula tá ótimo. Só a logo do Elmo que podia botar só o M, ou a palavra Elmo (sem capacete de respiração assistida). Dá certo?

Já deu certo. Sugestão feita.

**Comment by saracafe** [comment]
Ontem houve reunião de treinamento e o link já está na bio do instagram.
