### ISSUE TITLE
[01/06] Apresentação do iSUS para o Comitê Executivo Sesa

### ISSUE THREAD

**Issue by saracafe** [EscolaDeSaudePublica/FeliciLab#127]
O iSUS será apresentado ao Comitê Executivo da Sesa e é importante dar um nota sobre isso.

**Comment by Clarisse1983** [comment]
O iSUS foi finalmente apresentado ontem para o Comitê Executivo da Sesa e foi sucesso absoluto. Vou fazer a nota hoje e programar a publicação.
