### ISSUE TITLE
Divulgação Identidade Digital da Saúde: levantar requisitos com equipe

### ISSUE THREAD

**Issue by Clarisse1983** [EscolaDeSaudePublica/FeliciLab#13]
A ideia aqui é entender se o ID Saúde vai ter melhorias visuais e de narrativas, com o objetivo de ficar mais claro para as pessoas o que é a solução, para que serve, e como ela se conecta com as demais.

**Comment by Clarisse1983** [comment]
Ontem reunimos com Samara, BA do ID Saúde, para conversar sobre o projeto, sobre como vai ser a interface - se vamos ter um site, se vai ser uma página de autenticação, se vamos fazer o link dele com o projeto do Cadastro de profissionais de Saúde do Trello. Samara ficou de marcar reunião com Uirá para definir.

**Comment by Clarisse1983** [comment]
Fechando as demandas de produção de identidade visual, uma vez que são atribuições do Designlab e já estão sendo mapeadas por eles.

**Comment by uira** [comment]
Na verdade, sendo esse o contexto, acredito que a demanda deveria ser direcionada para análise do DesignLab, e eles fecham, se for o caso.

Faz sentido @RaniGub @Clarisse1983 ?

**Comment by RaniGub** [comment]
Prevista na Board do Designlab. Tarefa encerrada.
