### ISSUE TITLE
[09/06] Dia da Imunização

### ISSUE THREAD

**Issue by saracafe** [EscolaDeSaudePublica/FeliciLab#130]
Fazer um post para o blog refletindo no insta sobre imunização no SUS, com foco na vacina de Covid-19.

A ideia é pegar as fotos das pessoas felicilabers que já foram vacinadas. Mas claro, as que se sentirem a vontade de enviar sua foto para a publicação.

**Comment by Clarisse1983** [comment]
Ascom vai fazer uma postagem com essa mesma ideia. Então vamos fazer repost do conteúdo deles.
