### ISSUE TITLE
[11/06] Criar publicação para o Dia do Educador Sanitário

### ISSUE THREAD

**Issue by saracafe** [EscolaDeSaudePublica/FeliciLab#132]
## **Objetivo**

**Como** pessoa usuária das redes sociais do felicilab
**Quero** homenagear o educador sanitário
**Para** me sentir representado

## **Contexto**

Dia 11 é dia do Educador Sanitário. Iremos falar sobre esse movimento que deu origem ao SUS, e descendo o recorte para a Escola e a missão de educação permanente de trabalhadores da saúde. Vamos fazer um post para o blog e para instagram. 

## **PubliciLab**

- [x] Pesquisar sobre o tema
- [x] Escrever um texto para blog e instagram
- [x] Revisão do conteúdo

## **DesignLab**

- [x] Pesquisar referências sobre o tema
- [x] Criar as artes: para blog (imagem grande mais horizontalizada e thumbnail de destaque), instagram e canal no telegram (pode ser a mesma do intagram)

## **Critérios de Aceitação**

- [ ] Visualizar o conteúdo 
**Dado que** sou uma usuária da internet 
**Quando** visito o instagram do felicilab
**então** eu visualizo e interajo com a publicação

## Observações
Links de apoio e informações adicionais

**Comment by saracafe** [comment]
Card atualizado

**Comment by pauloamoreira** [comment]
@Clarisse1983 e @saracafe segue artes para 1) instagram/telegrama, 2) blog - horizontal e 3) blog - thumbnail (os arquivos estão disponíveis no drive do PubliciLab):
![dia_educador_sanitario_instagram](https://user-images.githubusercontent.com/79201419/121558484-1bc08a00-c9ec-11eb-81c4-5415df1709c2.png)
![dia_educador_sanitario_horizontal-blog](https://user-images.githubusercontent.com/79201419/121558507-20853e00-c9ec-11eb-9115-0d3ac3e60a2b.png)
![dia_educador_sanitario_thumbnail](https://user-images.githubusercontent.com/79201419/121558514-23802e80-c9ec-11eb-8bd5-9207f0c0ce4b.png)

**Comment by saracafe** [comment]
Texto: https://docs.google.com/document/d/1UkmMOrpbAGbkZ3qVcVPojyM-EybEJPq8alfFh5-UjNI/edit?usp=sharing

**Comment by Clarisse1983** [comment]
@pauloamoreira acho que essa sobreposição do coraçãozinho sobre as palavras investiga. alerta. orienta. sobrepôs e poluiu o card.  Acho que sem essas palavras vai ficar menos congestionado. Vamos tentar?

**Comment by saracafe** [comment]
Texto: https://docs.google.com/document/d/1UkmMOrpbAGbkZ3qVcVPojyM-EybEJPq8alfFh5-UjNI/edit?usp=sharing

**Comment by pauloamoreira** [comment]
@Clarisse1983 segue peças com alteração sugerida (os arquivos no drive foram substituídos por estes):
![dia_educador_sanitario_instagram2](https://user-images.githubusercontent.com/79201419/121709667-2b54d700-caaf-11eb-962d-b7059f82b56b.png)
![dia_educador_sanitario_thumbnail2](https://user-images.githubusercontent.com/79201419/121709699-327be500-caaf-11eb-9752-55021a2c0b07.png)
![dia_educador_sanitario_horizontal-blog2](https://user-images.githubusercontent.com/79201419/121709723-3871c600-caaf-11eb-85b1-315b43dd38bd.png)
