### ISSUE TITLE
[12/06] Criar publicação A ciência e o amor

### ISSUE THREAD

**Issue by saracafe** [EscolaDeSaudePublica/FeliciLab#133]
## **Objetivo**

**Como** pessoa usuária das redes sociais do felicilab 
**Quero**  mostrar casais das ciências
**Para** me sentir representado 

## **Contexto**

Dia 12, é o dia dos namorados. Vamos aproveitar o contexto para buscar casais no campo da ciência que se ajudaram na criação de inovações e em produções científicas. Referência: Sartre e Simone de Beauvoir, Marie Curie e Pierre Curie, https://www.bbc.com/portuguese/internacional-43092590

## **PubliciLab**

- [x] Pesquisar sobre o tema 
- [x] Escrever texto para instagram
- [x] Revisão do conteúdo

## **DesignLab**

- [x] Pesquisar referências sobre o tema
- [x] Criar arte para o instagram 

## **Critérios de Aceitação**

- [ ] Visualizar o conteúdo
**Dado que** sou uma usuária da internet 
**Quando**  visito o instagram do felicilab
**então** eu visualizo e interajo com a publicação

## Observações
Links de apoio e informações adicionais

**Comment by saracafe** [comment]
Card atualizado

**Comment by pauloamoreira** [comment]
@Clarisse1983 e @saracafe segue arte para aprovação - este arquivo também foi disponibilizado no Drive do PubliciLab:
![a_ciência_e_o_amor](https://user-images.githubusercontent.com/79201419/121691497-6fd77700-ca9d-11eb-8e3f-fba531c6b712.png)

**Comment by saracafe** [comment]
Texto: https://docs.google.com/document/d/1EjTTO4qnNTB2CUH-vkBf6Oz4FvIiikqr83AXJE65z4w/edit?usp=sharing

**Comment by Clarisse1983** [comment]
@pauloamoreira tá bela, simples e leve. Só o texto que sugiro uma mudança: Conheça a história de casais que mudaram, juntes, a história da Ciência e da Inovação no mundo

**Comment by pauloamoreira** [comment]
@Clarisse1983, atualizei a arte, de acordo com sua orientação (este novo arquivo substituiu o anterior no drive):
![a_ciência_e_o_amor_2](https://user-images.githubusercontent.com/79201419/121734358-0d956b00-cacb-11eb-8834-09709b99fd73.png)

**Comment by Clarisse1983** [comment]
Massa @pauloamoreira! É isso!
