### ISSUE TITLE
[17/06] Divulgação Oficina de Latex

### ISSUE THREAD

**Issue by saracafe** [EscolaDeSaudePublica/FeliciLab#137]
Será a segunda divulgação para a Oficina de Latex que será realizada dia 24/06.

**Comment by saracafe** [comment]
Saber com a Ascom se a oficina será realizada no canal FeliciLab ou da ESP.

**Comment by Clarisse1983** [comment]
A oficina será amanhã, 24/06, e Ascom está fazendo a divulgação desde hoje, e nós tb, desde semana passada.
