### ISSUE TITLE
Atualizar vídeo de 1 ano do FeliciLab

### ISSUE THREAD

**Issue by saracafe** [EscolaDeSaudePublica/FeliciLab#139]
## **Objetivo**

**Como** publico externo  
**Quero** ter conhecimento do vídeo 
**Para** saber a história do FeliciLab neste primeiro ano de existência

## **Contexto**

- O vídeo já foi produzido e divulgado internamente no aniversário de 1 ano, mas precisamos fazer atualizações no material para divulgar nas nossas plataformas.

## **PubliciLab**

- [ ] Marcar uma reunião de refinamento específico para avaliar a proposta de mood board com Uira, Oxto, Claris e Ana
- [ ] Fornecer os materiais necessários

## **Critérios de Aceitação**

- [ ] Visualizar o vídeo nos nossos canais  
**Dado que** que sou uma usuária da internet 
**Quando** visito as redes sociais do FeliciLab e da ESP
**então** eu visualizo e interajo com a publicação

## Observações
Link do mood board https://miro.com/app/board/o9J_l_jF2jw=/

**Comment by Clarisse1983** [comment]
Fechando essa issue porque essa tarefa não foi para frente, não investimos nisso. Se formos produzir outro vídeo comemorativo, será de outra data, com nova pesquisa etc e tal.
