### ISSUE TITLE
Criar publicação sobre vídeo do Luis

### ISSUE THREAD

**Issue by saracafe** [EscolaDeSaudePublica/FeliciLab#140]
O Ludes produziu um vídeo para explicar a ideia de um artigo sobre jogos. O Luis faz parte desse projeto e por isso vamos publicar o vídeo no instagram.

**Comment by Clarisse1983** [comment]
Dei uma editada lá no conteúdo no insta. A ideia não era só divulgar o vídeo, mas a própria ideia presente no vídeo, dos sistemas de informação no cotidiano. Isso é que legal: eles escreveram um artigo, e pra não esperar de braços cruzados que oa rtigo fosse lido, eles fizeram um teaser explicando a ideia geral do artigo. Vale de inspiração pra gente.
