### ISSUE TITLE
[30/06] Papinho tech especial 

### ISSUE THREAD

**Issue by MayaraMonte** [EscolaDeSaudePublica/FeliciLab#143]
## **Objetivo**

**Como** time iSUS Discovery 
**Quero** fazer uma chamada geral
**Para** convidar todos os felicilabers para um workshop 

## **Contexto**

- O papinho tech é um momento de oficinas realizadas de acordo com a necessidade dos integrantes do time iSUS, porém, conseguimos chamar uma convidada para falar sobre um tema muito importante e gostaríamos de compartilhar essa oportunidade e abrir a agenda para quem quiser participar.

## Observações
Opção de texto: 

Olá Felicilabers, dia lindo procês!
Nós do time iSUS Discovery estamos passando por aqui para convidar geral a participar com a gente de uma edição especial do nosso papinho tech. 

📆 Dia: 30.06.2021 às 19h 

👩🏻‍🦱 Convidada especial: Awa Maia
A Awa é bacharela em Comunicação com ênfase em Publicidade pela UFMG e Especialista em Design de Interação pela PUC Minas. Em sua trajetória profissional, trabalhou com criação publicitária, marketing, webdesign e hoje atua como designer de interação na DTI Digital. Desde a faculdade se interessa por estudos de gênero e segue na busca por fazer do mundo um lugar menos desigual.

💬 Sobre o tema: A linguagem possui um papel de agente social. É através dela que nos relacionamos com o mundo, que criamos significado para as coisas e ela está presente o tempo todo em nossas interfaces. A forma como escrevemos pode reforçar estereótipos e preconceitos, entre eles, vieses de gênero. Muitas tentativas de contornar esses vieses, como uso de "x" e "@" para neutralidade de gênero, se mostram problemáticas na questão de acessibilidade e não conseguem ainda ser incorporadas na fala, portanto não causam transformações reais.

📣 Vem com a gente refletir sobre esse assunto! Para participar é só entrar no Google Meet, no link https://bit.ly/3x6W19d

Opção de banner: 
https://drive.google.com/file/d/1yVfXh-nTkRmrPdnQy6exSAsWpl_HYM1d/view?usp=sharing

**Comment by pauloamoreira** [comment]
@MayaraMonte segue arte para aprovação (arquivo também foi disponibilizado no drive do PubliciLab):
![Papinhotech_LinguagemNeutra-quadrada-Instagram_Telegram](https://user-images.githubusercontent.com/79201419/122825992-05061700-d2b9-11eb-91e6-37c485b75a93.png)

**Comment by Clarisse1983** [comment]
@pauloamoreira achei massa, exceto esse fundo rosa/roxo, muito sexista isso ainda hehehe

**Comment by pauloamoreira** [comment]
@Clarisse1983 @MayaraMonte e @saracafe segue nova arte, com alterações na paleta de cores:
![Papinhotech_LinguagemNeutra-quadrada-Instagram_Telegram_2](https://user-images.githubusercontent.com/79201419/122947295-6dec9e00-d350-11eb-9680-567148d59c36.png)

**Comment by pauloamoreira** [comment]
ok, @Clarisse1983. segue sem marca iSUS (também vou substituir no drive):
![Papinhotech_LinguagemNeutra-quadrada-Instagram_Telegram_2](https://user-images.githubusercontent.com/79201419/122953504-261c4580-d355-11eb-9a95-2c925a7dc6a1.png)

**Comment by Clarisse1983** [comment]
Issaê, @pauloamoreira. Gracias!

**Comment by Clarisse1983** [comment]
Meu povo, tô tentada a articular a transmissão desse evento aqui tb no YouTube da ESP. O que acham?

**Comment by saracafe** [comment]
Houve uma alteração na data, agora será dia 30/06 às 19h, via Meet, vamos gravar e disponibilizar na página do Youtube. Vamos também pedir a ascom para fazer a divulgação.

**Comment by Clarisse1983** [comment]
@pauloamoreira, depois de mil idas e vindas, vou pedir um último ajuste na arte, que é acrescentar o endereço da sala: meet.google.com/nrs-iets-oma
Até te coloquei na agenda. ;)

**Comment by pauloamoreira** [comment]
@Clarisse1983 @saracafe e @MayaraMonte  segue nova arte com endereço da sala (também vou substituir no drive):
![Papinhotech_LinguagemNeutra-quadrada-Instagram_Telegram_3](https://user-images.githubusercontent.com/79201419/123691491-122c8400-d82c-11eb-9a10-9e000baecbbf.png)

**Comment by pauloamoreira** [comment]
.texto do endereço encurtado:  https://bit.ly/3x6W19d
