### ISSUE TITLE
Revisar narrativas home site FeliciLab e página de conteúdo extra do iSUS

### ISSUE THREAD

**Issue by Clarisse1983** [EscolaDeSaudePublica/FeliciLab#145]
## **Objetivo**

**Como** pessoa usuária visitando o site do FeliciLab ou a home de conteúdos extras do livro do capítulo do iSUS no livro da Escola
**Quero** visualizar as respectivas homes com chamadas para os conteúdos
**Para** saber do que tratam e decidir sobre o clique

## **Contexto**

- As propostas de home do site do FeliciLab e da página de conteúdos extras do capítulo do iSUS no livro da Escola estão montadas pelo Daniel, e precisamos reescrever as chamadas para os conteúdos presentes, de modo que as pessoas usuárias saibam do que tratam e possam se interessar pelo clique.

## **PubliciLab**

- [x] Revisar os textos atualmente presentes em https://sus.ce.gov.br/felicilab e https://i.sus.ce.gov.br/extra/
- [x] Pesquisar em páginas de referência bons exemplos de chamadas. Ex: Nexo Jornal

## **Critérios de Aceitação**

- [ ] Visualizar sites com homes atualizadas 
**Dado que** estou no site do FeliciLab ou na página de conteúdos extras sobre o iSUS
**Quando** vejo as respectivas homes  
**Então** encontro chamadas atualizadas para os conteúdos

## Observações
Links de apoio e informações adicionais

**Comment by saracafe** [comment]
Fazendo a revisão: https://docs.google.com/document/d/1Ty_q-13wW3bOzQaf7IlceSbtNcSTQhXgdj_zAw-qcTw/edit?usp=sharing

**Comment by pauloamoreira** [comment]
@danielgula e @Clarisse1983 reviso o material do felicilab. está no processo de revisão no conteúdo do iSUS.

**Comment by Clarisse1983** [comment]
Pronto, @danielgula, revisão concluída.
