### ISSUE TITLE
Criar orientações para os participantes do #Cuida!

### ISSUE THREAD

**Issue by danielgula** [EscolaDeSaudePublica/FeliciLab#154]
## **Objetivo**

**Como** colaborador
**Quero** conhecer as melhores práticas de gravação de voz
**Para** entregar os áudios com melhor qualidade para podcast Cuida!

## **Contexto**

Com o lançamento semanal do podcast Cuida, sentimos a necessidade de dar orientações para as pessoas do time que colaboram narrando os textos do roteiro criados pelo publicilab. Dessa forma, a equipe do designlab vai criar um texto com dicas para ter uma melhor captação do áudio e evitar problemas na hora da edição do programa semanal.

### **Designlab**
- [x] Criar orientações em formato de texto
- [x] Criar uma arte conceitual
- [x] arte para Instagram
- [x] arte para Blog

### **Publicilab**
- [x] Criar uma chamada para "5 dicas para gravar melhor seus áudios"
- [x] Escolher melhor canal para publicar

## **Critérios de Aceitação**

**Dado que** sou colaborador do Cuida
**Quando** gravo um áudio
**então** consigo entregar um arquivo com qualidade para o podcast

**Comment by danielgula** [comment]
Segue minha proposta para o texto das dicas:

Nos adoramos quando vocês nos ajudam a construir o #Cuida com a nossa cara. E para que possamos ter episódios mais incríveis ainda do nosso podcast felicilaber, separamos algumas dicas legais para que você possa gravar seus áudios com a melhor qualidade.

1 - Nem todo mundo tem o super mega blaster gravador do Washington =). Então, para quem não tem microfone profissional, pode gravar pelo próprio gravador do celular. Ao gravar um áudio, coloque o celular ou microfone na frente e abaixo da boca, na altura do pescoço. Isso vai gerar um som mais natural e equilibrado.
2 - A correria do dia-a-dia nos deixa ligado no 220 direto. Que tal aproveitar para gravar o cuda com mais calma? Falar devagar ajuda aos ouvintes entenderem melhor nosso programa. Respire e fale calmamente, dando pausas quando terminarem orações ou depois das vírgulas no texto.
3 - O #Cuida tem a proposta de ser um programa leve e descontraído com a cara do Felicilab. Ao grava, seja natural, você mesmo, como se estivesse conversando com o colega.
4 - Aqui vai um segredinho: quer saber qual o melhor canto para se gravar um áudio de qualidade? Então faça dentro do carro! Isso mesmo, o carro é um local fechado, onde os bancos de tecido e as partes internas do chassi, que são onduladas e cobertas de material absorvente, garantem uma filtragem de ruídos e uma ótima redução da reverberação. Experimente!
5 - Tudo bem. Tem gente que vai dizer: caramba! Não tem como eu gravar dentro de um carro. E agora? Procure um lugar silencioso, de preferência que seja aberto. Se for em um lugar fechado, evitar um ambiente com ar-condicionado, com paredes retas ou divisórias de vidro e sem objetos, pois isso aumenta a reverberação do som que acaba gerando ruídos na captação de áudio pelo microfone de um celular. Um ambiente com muitos objetos e cortinas, por exemplo, filtra a propagação do som, evita ruídos desagradáveis e destaca a sua voz!
É isso! E se você tem alguma super dica para compartilhar com a gente, cuida e fala pra gente!

**Comment by Clarisse1983** [comment]
Nós adoramos quando você nos ajuda a construir o Cuida! com a nossa cara. Precisamos de você para fazer nosso podcast acontecer. E para que possamos ter episódios mais incríveis ainda, criamos algumas dicas legais para que você possa gravar seus áudios com a melhor qualidade.
1 - Nem todo mundo tem o super mega blaster gravador do Washington =). Então, para quem não tem microfone profissional, pode gravar pelo próprio gravador do celular, inclusive enviando diretamente como uma mensagem de áudio. Ao gravar um áudio, coloque o celular ou microfone na frente e abaixo da boca, na altura do pescoço. Isso vai gerar um som mais natural e equilibrado.
2 - A correria do dia-a-dia nos deixa ligados nos 220 volts direto. Que tal aproveitar o momento de gravar o Cuida! para dar uma respirada e criar com mais calma? Falar com tranquilidade ajuda os ouvintes a entenderem melhor nosso programa. Dê pausas quando terminarem orações e depois das vírgulas no texto.
3 - O Cuida! tem a proposta de ser um programa leve e descontraído, com a cara do Felicilab. Ao gravar, seja natural, você mesmo, como se estivesse conversando com o colega.
4 - Aqui vai um segredinho: quer saber qual o melhor lugar para se gravar um áudio de qualidade? Dentro do carro! Isso mesmo, o carro é um local fechado, onde os bancos de tecido e as partes internas do chassi, que são onduladas e cobertas de material absorvente, garantem uma filtragem de ruídos e uma ótima redução da reverberação. Experimente!
5 - Tudo bem se você não tiver como gravar dentro de um carro porque não possui um, ou não se sente confortável para fazer no veículo de outra pessoa. E agora? Procure um lugar silencioso, de preferência que seja aberto. Se for em um lugar fechado, evitar um ambiente com ar-condicionado, com paredes retas ou divisórias de vidro e sem objetos, pois isso aumenta a reverberação do som, que acaba gerando ruídos na captação de áudio pelo microfone de um celular. Um ambiente com muitos objetos e cortinas, por exemplo, filtra a propagação do som, evita ruídos desagradáveis e destaca a sua voz!
É isso! E se você tem alguma super dica para compartilhar com a gente, cuida e nos envia, que a gente adooooraaaa! Gratidão por seu apoio e disposição! <3

**Comment by Clarisse1983** [comment]
@danielgula, revisei o texto e coloquei uma abertura mais direcionada, nós falando "para você", que é pra gente enviar diretamente para quem vai fazer a gravação, sabe? E aí penso que vale sim fazer uma are bacana, pra gente mandar junto do texto via telegram, e também uma postagem no blog  - 5 dicas para turbinar seu áudio para um Cuida! e deixá-lo um sucesso! Porque aí fica lá como conteúdo externo também, útil para a criação de qualquer material com áudio, e que a gente pensa que é meio óbvio, mas não é. Jogar no canal geral assim do nada, não faz sentido. Tem que ser uma ação direcionada. Ah, e já propus à Sara e vou propor à toda a equipe fazermos uma cerimônia de feedback amanhã, de 16h às 17h, sobre o Cuida! Que tal?

**Comment by danielgula** [comment]
![5-dicas](https://user-images.githubusercontent.com/39468037/127363233-b1d347c3-e170-494a-b22a-d0a2b32a286f.jpg)

Segue proposta para aprovação. É necessário atribuir os créditos dessa imagem, pois não temos uma conta para usar imagens comercialmente. Segue texto a ser incorporado:

"Arte original de pch.vector / Freepik"

**Comment by Clarisse1983** [comment]
@danielgula, faz um formato mais horizontal, pra gente usar como imagem de destaque no blog, please.

**Comment by danielgula** [comment]
Segue modelo horizontal

![5-dicas-thumb](https://user-images.githubusercontent.com/39468037/127538592-a31643fd-8350-4d8b-a5d3-24aaa8f70c26.jpg)
