### ISSUE TITLE
Escrever a seção 'Com quem eu falo' para onbording

### ISSUE THREAD

**Issue by Clarisse1983** [EscolaDeSaudePublica/FeliciLab#158]
## **Objetivo**

**Como** nova pessoa colaboradora do FeliciLab 
**Quero** acessar informações sobre pessoas responsáveis por orientações
**Para** saber quem buscar na existência de dúvidas e demandas

## **Contexto**

- Escrever o texto com as informações objetivas sobre quem procurar em determinadas situações. Exemplo: para solucionar questões de TI - abrir chamado no sistema, para saber informações sobre a bolsa - consultar administrativo através do telefone tal. Essas informações serão disponibilizadas no onbording e também no site para colaboradores chegantes e atuais.

## **PubliciLab**

- [x] Pesquisar as informações essenciais
- [x] Escrever o texto

## **Critérios de Aceitação**

- [x] Visualizar orientações sobre pessoas/setores responsáveis 
**Dado que** sou pessoa colaboradora do FeliciLab  
**Quando** apresento dúvidas sobre a quem consultar ou como proceder em determinadas situações, ou mesmo antes das apresentações  
**Então** recebo informações no onbording e tenho disponíveis no site do FeliciLab 

## Observações
Links de apoio e informações adicionais

**Comment by saracafe** [comment]
https://docs.google.com/document/d/19NCBAXywTLtvKQKqr076KzS-wYVPcOjpCUWj1GnxUxI/edit?usp=sharing
