### ISSUE TITLE
Criar evento de terapias integrativas #LiberouGeral

### ISSUE THREAD

**Issue by saracafe** [EscolaDeSaudePublica/FeliciLab#162]
## **Objetivo**

**Como** colaborador do ESP/CE
**Quero** divulgar o evento de terapias integrativas
**Para** para que os colaboradores tenha um momento de relaxamento

## **Contexto**

- Sexta feira é dia de Liberou Geral, o Genilton sugeriu uma atividade de terapias integrativas (massoterapia, Quick Massage e ThetaHealing) com a presença de alguns terapeutas. O evento ocorrerá no dia 30/07, das 09h às 12h, na ESP/CE. O RH já foi consultado sobre a possibilidade de transporte para terapeutas fazerem a atividade presencial.  Sugestão de nome do evento: #SextouZen

## **PubliciLab**

- [x] Já foi enviado a proposta para o RH (Clívia)
- [x] Pedido do transporte para os três terapeutas (Nicolas solicitou junto a Luciana)
- [x] Oficializar a solicitação do transporte - Nicolas NUGAD - Sala (Lucia) e transporte (Deyane)
- [x] Solicitar apoio para organização do local (água, aparelho de som, notebook, músicas calmas) - RH Clívia
- [x] Definir horário com terapeutas e Clívia do RH. Melhor horário: 09:00 às 12:00.
- [x] Alinhar com o RH: material de apoio para os terapeutas, ambientação do espaço (espaço com acústica adequada, com o máximo de silêncio), logística dos colaboradores que irão auxiliar na organização do evento, caixa de som, lenços (solicitação da terapeuta Mary), água para os terapeutas.
- [x] Produção de release a ser enviado para Ascom
- [x] Criar formulário com arte (@danielgula) e release (@saracafe)
- [x] Enviar email para ASCOM fazer a divulgação do evento
- [x] Fazer um texto para redes sociais e blog.
- [x] Fazer um vídeo para stories de divulgação do evento (parecido com o Papinho Tech).
- [x] Fazer a divulgação nos grupos internos.
- [x] Cobertura do evento @saracafe 
- [x] Solicitar assessoria de imprensa pela ASCOM
- [x] Solicitar cobertura fotografia pela ASCOM
- [x] Criar horário limite para enviar formulário
- [x] Próximo evento: deixar número de celular para os interessados marcarem o horário.
- [x] Anaísa (996261886) se ofereceu como consteladora familiar para o próximo evento.
- [x] Elaborar relatório pós evento.

## **DesignLab**

- [x] Pesquisar algumas referências de arte sobre terapias integrativas, saúde mental, autocuidado
- [x] Fazer uma arte para instagram/telegram, imagem horizontal para blog e thumbnail
- [x] Sugestão de nome: #SextouZen e dar destaque com letras e cores diferentes para "TouZen" (ainda vai ser escolhido o nome)
- [x] Divulgar os instagrans dos terapeutas (@maryalbuquerqueterapeuta @movimentosaudemental)
- [x] Criar arte para Google Form

## **Critérios de Aceitação**

- [x] Visualizar e participar do evento 
**Dado que** sou colaborador da ESP  
**Quando** fui informado do evento   
**então** eu participo da atividade

## Observações
ThetaHealing é uma uma técnica onde o terapeuta e o paciente ficam conectados com o Criador de Tudo o Que É, Deus, acessando a frequência theta através de uma meditação simples e focada com o objetivo de realizar curas em todos os níveis de crenças e áreas da vida do cliente.

Terapeutas:

- Mary Albuquerque, terapeuta ThetaHealing e consteladora familiar (@maryalbuquerqueterapeuta)
- Massoterapeutas do Movimento de Saúde Mental Comunitário do Bom Jardim (@movimentosaudemental)

Observações:

[Como o evento foi elaborado](https://docs.google.com/document/d/1ZtPK042s5BVgFSY5Ys6r_5rrUaUOBtmYoLKbnQKVm_k/edit?usp=sharing)

**Comment by Clarisse1983** [comment]
@danielgula, sobre a arte, podemos fechar o nome em #SextouZen: cuidando de quem cuida. E aí no card limpar os textos e deixar só a data e o nome do evento, porque as demais informações a gente coloca no texto do serviço. E tá linda, parabéns! =)
