### ISSUE TITLE
Criar vídeo do evento NIT em transformação

### ISSUE THREAD

**Issue by anapvcv** [EscolaDeSaudePublica/FeliciLab#165]
## **Objetivo**

**Como** uma pessoa usuária das redes sociais do Felicilab
**Quero** saber como foi o evento
**Para** conhecer melhor o Felicilab

## **Contexto**

- O Núcleo de Inovação Tecnológica da ESP foi oficializado com a publicação da Política de Inovação da Escola de Saúde Pública no Diário Oficial do Estado do Ceará. Por isso, no dia 08 de julho ocorreu o evento NIT em Transformação, de forma presencial e remota, para atualizar o novo contexto, apresentar os novos modelos de gestão, dialogar sobre as modalidades de trabalho entre outras questões. A Ana fez a cobertura audiovisual do evento. 

## **Publicilab**

- [x] Edição e montagem das imagens
- [x] Publicar o vídeo nos canais: youtube e instagram
- [x] Escrever uma legenda para as redes sociais
- [x] Enviar o vídeo para a Ascom indexar no material divulgado no site da ESP

## **Critérios de Aceitação**

- [x] Visualizo o vídeo
**Dado que** sou uma pessoa usuária das redes sociais do Felicilab
**Quando** tenho acesso o vídeo
**então** visualizo e interajo com a publicação

## Observações
Links de apoio e informações adicionais

**Comment by Clarisse1983** [comment]
@anapvcv, um card não está concluído enquanto todas as etapas do escopo não estão concluídas. Já foi publicado o vídeo no nosso canal no YouTube e no instagram?

**Comment by anapvcv** [comment]
> @anapvcv, um card não está concluído enquanto todas as etapas do escopo não estão concluídas. Já foi publicado o vídeo no nosso canal no YouTube e no instagram?

ai, desculpa. não estão. eu achei que o card era referente apenas ao processo de edição e montagem.

**Comment by saracafe** [comment]
@anapvcv sobe o link do vídeo aqui para a gente postar no youtube e no instagram

**Comment by anapvcv** [comment]
> @anapvcv sobe o link do vídeo aqui para a gente postar no youtube e no instagram

segue o link do vídeo: https://drive.google.com/file/d/1rydnFb7K9j8iuGmj0qwepWMnxjQK5Mnp/view?usp=sharing

**Comment by saracafe** [comment]
Enviei email para ascom com o link do vídeo NIT em Transformação para ser indexado ao material divulgado no site da ESP. Já responderam dizendo que vão colocar lá.
