### ISSUE TITLE
Produzir curta metragem sobre parceria entre Sepos e ESP na execução de políticas públicas

### ISSUE THREAD

**Issue by Clarisse1983** [EscolaDeSaudePublica/FeliciLab#168]
## **Objetivo**

**Como** equipe de comunicação da Inovação
**Quero** produzir materiais audiovisuais
**Para** criação de um curta metragem documental sobre esse parceria entre Sepos e ESP na Agenda de Prioridades em Saúde

## **Contexto**

- A Escola de Saúde Pública do Ceará está envolvida na construção e implantação da Agenda de Prioridades da Secretaria Executiva de Políticas de Saúde. São várias diretorias da ESP envolvidas, e nós, da Diretoria de Inovação e Tecnologia, vamos participar ativamente de várias entregas, resultantes dos eixos de Tecnologias para Monitoramento e Avaliação de Programas e Políticas, Comunicação e Informação em Saúde e Tecnologias em Serviços de Saúde. Esse épico consiste num conjunto de tarefas para acompanhamento das reuniões de articulação e planejamento e todos os outros encontros previstos para a concretização dessa Agenda, com o objetivo de reunir materiais audiovisuais que sirvam para a produção de um documentário sobre esse processo, mostrando que as políticas e parcerias se fazem em processo. Uma das atividades já fruto dessa articulação é a realização da Oficina de Design de Serviço. conduzida pelo DesignLab, direcionada aos colaboradores da Sesa.

## **PubliciLab**

- [ ] Produzir um briefing para elaboração do(s) roteiro(s) do(s) produto(s) final(ais)
- [ ] Acompanhar os eventos e reuniões para coleta de imagens e depoimentos
- [ ] Filmar Oficina de Design de Serviço, de 4 a 6 de agosto na ESP

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [ ] Produzir filme sobre parceria entre Sepos e ESP 
**Dado que** sou pessoa comunicadora na Inovação 
**Quando** acompanho encontros e atividades entre Sepos e ESP
**Então** tenho materiais para produção de filme sobre Agenda de Prioridades da Saúde

## Observações
Links de apoio e informações adicionais

**Comment by danielgula** [comment]
Foi feito registro audiovisual da Oficina, bem como um artefato impresso com o legado de todo o processo. A demanda será encerrada e quando houverem outros encontros novas demandas serão criadas.
