### ISSUE TITLE
Criar vídeo-registro #SextouZen

### ISSUE THREAD

**Issue by Clarisse1983** [EscolaDeSaudePublica/FeliciLab#172]
## **Objetivo**

**Como** pessoa usuária dos canais de comunicação do FeliciLab
**Quero** ver o vídeo do #SextouZen  
**Para** saber como foi a experiência

## **Contexto**

- Realizamos, com apoio da DIAFI, do RH e da Ascom, o #SextouZen - cuidando de quem cuida, evento que nasceu das possibilidades de integração e cuidado sinalizadas pelo #LiberouGeral e das nossas ótimas conversas internas. Genilton coordenou o processo e foi um sucesso. Coletamos depoimentos de todes os participantes e agora é hora de criar um vídeo-registro desse momento, para dar voz e visibilidade à essa semente de amor e cuidado.

## **PubliciLab**

- [x] Fazer um roteiro para a construção desse vídeo
- [x] Editar vídeo com as imagens coletadas
- [x] Definir um prazo para publicação
- [x] Publicar

## **Critérios de Aceitação**

- [x] Visualizar vídeo sobre #SextouZen
**Dado que** sou usuária dos canais de comunicação do FeliciLab 
**Quando** estou no IGTV instagram  
**Então** visualizo vídeo sobre o #SextouZen

## Observações
https://docs.google.com/document/d/1OmwCuJQ_iK6G8orG7KYXvFvYrEzbXhJ73UbjpgZ7uL8/edit

Pasta com os vídeos: https://drive.google.com/drive/folders/1ehkfzeHHV9lFO-tOk_G-4z9KORaZnGHh
https://photos.google.com/share/AF1QipNemeolzR7rznojkt3O1XaLec8Xl4vT-1Mc0A-A3Arv3D-4sgHaXN06eaofyct12A

[Guia com o nome dos participantes que forneceram os relatos em vídeo (o link no nome vai direto para o vídeo)](https://docs.google.com/document/d/1XI20kAt9456G9c6ThLITWqUlWOpA-Xie/edit)

**Comment by anapvcv** [comment]
proposta de vídeo para o sextou zen: https://drive.google.com/file/d/1dQ86fqkHJfQ1P4ZVxlIdiGFXJD1otS2x/view?usp=sharing

**Comment by Clarisse1983** [comment]
- Inserir identificação das pessoas;
- Uma descrição curta no final sobre o que é o #SextouZen

**Comment by anapvcv** [comment]
proposta de corte final para o sextou zen: https://drive.google.com/file/d/1z5N3bcWf45qsnHAx_UrqUgqxq-Jv7apb/view?usp=sharing
