### ISSUE TITLE
Criar release sobre a Semana de Inovação das ICT's do Ceará

### ISSUE THREAD

**Issue by saracafe** [EscolaDeSaudePublica/FeliciLab#174]
## **Objetivo**

**Como** pessoa comunicadora da inovação na ESP
**Quero** produzir um release  
**Para** divulgar o material informativo para a imprensa e pessoas interessadas

## **Contexto**

- Nos dias 18 a 22 de outubro, a ESP irá participar da Semana de Inovação em parceria com outras ICT's vinculadas ao Governo do Estado. A ementa do evento e a programação já estão montadas. O próximo passo é  fazer um material informativo (release) para ser divulgado aos parceiros, a imprensa e público interessado. 

## **PubliciLab**

- [x] Estudar o material, as ementas e o cronograma do evento
- [x] Fazer a proposta de texto para o release

## **Critérios de Aceitação**

- [ ] Produzir um release para divulgação do evento   
**Dado que** sou pessoa comunicadora da inovação da ESP
**Quando** produzo um release
**então** divulgo o evento para pessoas interessadas 

## Observações
https://drive.google.com/drive/folders/1oeXh83EQj_KFXOMKlVR4T3a_niU-5ZCk

**Comment by Clarisse1983** [comment]
@saracafe, a estrutura já está aqui, ó:
https://docs.google.com/document/d/1QzJb49Ebu9mtj9QtM-J0069SW1VhU_XTlGeOFk5PJTY/edit#heading=h.1v5tvoph8e2e
