### ISSUE TITLE
Bingão do #LiberouGeral

### ISSUE THREAD

**Issue by saracafe** [EscolaDeSaudePublica/FeliciLab#176]
## **Objetivo**

**Como** colaborador do NIT/FeliciLab  
**Quero** realizar um bingo presencial e online
**Para** atividade de integração do Liberou geral

## **Contexto**

- Durante essa semana houve uma limpeza na sala do NIT e foram encontrados alguns pertences de valor afetivo para os colaboradores. Então surgiu a ideia de fazer um bingão com esses objetos e outras surpresas, como chocolates e afins, em homenagem ao dia dos pais como atividade do #LiberouGeral, desta sexta (06). 

## **PubliciLab**

- [x] Escrever um texto para instagram e telegram
- [x] Publicar nos grupos e redes sociais

## **DesignLab**

- [x] Buscar referência sobre artes de bingo e dia dos pais
- [x] Montar a arte

## **Critérios de Aceitação**

- [x] Participo do bingão do Liberou Geral
**Dado que** sou colaborador do NIT/FeliciLab  
**Quando** fico sabendo do bingão do Liberou geral
**então** participo da atividade de integração

## Observações
Links de apoio e informações adicionais

**Comment by danielgula** [comment]
![Bingão](https://user-images.githubusercontent.com/39468037/128376237-829e3bc2-3920-4f21-b580-710295d5c15a.jpg)
Segue arte para aprovação e texto de atribuição de direito de imagem
Desenho original por gstudioimagen - Freepik

**Comment by saracafe** [comment]
Textou do #BingãodoFelicilab https://docs.google.com/document/d/1toAoisg8ewSnJo-pR74KvFj54Vcctl0pbsT952OiKAw/edit?usp=sharing
