### ISSUE TITLE
Liberou Geral com Bruna Nobre

### ISSUE THREAD

**Issue by geniltonfaheinajr** [EscolaDeSaudePublica/FeliciLab#182]
## **Objetivo**

**Como** colaborador do NIT/FeliciLab 
**Quero** assistir evento sobre saúde mental e autoconhecimento, com bloco de música ao vivo.
**Para** atividade de integração do Liberou geral

## **Contexto**

- Genilton sugeriu a ideia de realizar um Liberou Geral com a participação da artista Bruna Nobre, cantora, artista visual e escritora do livro Um amuleto para a o seu eu mais profundo. Ela se dispos a falar sobre saúde mental e como a arte pode auxiliar no processo de resgaste de si mesmo , além de falar sobre seu mais recente livro. Também haverá momento de despressurização com música ao vivo. Dia 27/08.

## **Publicilab**

- [x] Definir nome para o evento
- [x] Criar agenda na agenda FeliciLab
- [x] Escrever um texto para Telegram.
- [x] Enviar um release para Ascom fazer a divulgação nos grupos internos e redes sociais

## **DesignLab**

- [x] Elaborar arte para divulgação.

## **Critérios de Aceitação**

- [x] Participo do Liberou Geral
**Dado que** sou colaborador do NIT/FeliciLab
**Quando** fico sabendo do Liberou geral do dia 27/08
**então** participo da atividade de integração

## Observações
Foto da Bruna: https://drive.google.com/file/d/1wBPUzE-xeXtv9MV8Zn-louYbiDffEYiX/view?usp=sharing
Cantora, artista visual e escritora
https://drive.google.com/drive/folders/1HqhmUkmKx6IWcmlDpHkuHwhoJDYGUYyg?usp=sharing

**Comment by Clarisse1983** [comment]
@RaniGub @danielgula estamos com essa demanda de arte para o Liberou Geral do dia 27. Quem pode pegar?

**Comment by RaniGub** [comment]
@Clarisse1983 alinhe com o @danielgula para pegar a demanda. @danielgula o card tá na coluna "Tudão" no Zen.

**Comment by danielgula** [comment]
![image](https://user-images.githubusercontent.com/39468037/130492994-18378bf7-93da-42f2-a2d3-b774f4d1ccb9.png)
Proposta para validação

**Comment by RaniGub** [comment]
@Clarisse1983

**Comment by geniltonfaheinajr** [comment]
@danielgula deixei na pasta do Liberou outras imagens da Bruna e uma arte para você se inspirar. É mais a cara da Bruna e de sua proposta. Alinhamos na reunião que é interessante mudar essa fonte e o título: Liberou Geral - música e autonconhecimento, com Bruna Nobre.

https://drive.google.com/drive/folders/1HqhmUkmKx6IWcmlDpHkuHwhoJDYGUYyg?usp=sharing

**Comment by saracafe** [comment]
Release do evento: https://docs.google.com/document/d/1j-XffxJbDBbZsq4Im-Pu-UIgLI0njZSJKv1kunScCn4/edit?usp=sharing

**Comment by danielgula** [comment]
Nova proposta para a chamada
![image](https://user-images.githubusercontent.com/39468037/130807532-ab06c3e8-eebf-426a-a4e7-9743b1eddca1.png)

**Comment by Clarisse1983** [comment]
@danielgula põe uma linha fina embaixo de Liberou Geral, em fonte menor, com o texto: "Música e autoconhecimento para lidar com o hoje". No mais tá bacana.

**Comment by saracafe** [comment]
Na sexta, houve a gravação do evento. Será feita a edição do material para posterior divulgação nos canais da ESP e do FeliciLab.
