### ISSUE TITLE
Apresentar histórico de ações do primeiro ano de atividades do Felicilab

### ISSUE THREAD

**Issue by wforte88** [EscolaDeSaudePublica/FeliciLab#183]
## **Objetivo**

**Como** felicilaber
**Quero** apresentar o histórico de 1 ano do Felicilab
**Para** prestar contas das atividades desenvolvidas

## **Contexto**
O Publicilab produziu um relatório e um vídeo que resgatam os marcos do primeiro ano de funcionamento do Felicilab. Deve-se analisar esse material e estudar formatos e estratégias adequadas para publicizar o registro histórico.

## **Escopo**

- [x] escopo1

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [x] titulo  
**Dado que** algo  
**Quando** faço  
**então** resulta

## Observações
[Relatório de ações de 1 ano do Felicilab](https://docs.google.com/document/d/1sAQhAdrcRj0SM0uKyNUuKuUPJTdWYLCw7348TGX707M/edit#heading=h.dwsoj4y36w8y
)

**Comment by danielgula** [comment]
Esse card diz respeito a outro:

https://github.com/EscolaDeSaudePublica/FeliciLab/issues/59
