### ISSUE TITLE
Apoiar divulgação da defesa do Prêmio de Inovação

### ISSUE THREAD

**Issue by Clarisse1983** [EscolaDeSaudePublica/FeliciLab#185]
## **Objetivo**

**Como** pessoa usuária interessada em inovação
**Quero** assistir a premiação do 25 Concurso de Inovação da ENAP  
**Para** conhecer as experiências premiadas

## **Contexto**

- Estamos na final do 25 Concurso de Inovação da ENAP e a apresentação será no dia 16/09, de 14h30 às 17h. Precisamos divulgar e mobilizar as pessoas para esse momento. O link de transmissão será divulgado mais perto da data, o evento é aberto ao público.

## **PubliciLab**

- [x] Release sobre a cerimônia de apresentação
- [x] Enviar release para Ascom, solicitando divulgação (Acontece na ESP, matéria no site, instagram)

## **DesignLab**
- [x] Customizar a apresentação:
https://docs.google.com/presentation/d/19XrYsxy6EB_znmwL25yZ1G_j7oU_17YPo0ZSWu0nfwQ/edit#slide=id.ge8020ed4d8_0_170

## **Critérios de Aceitação**

- [x] Acompanhar transmissão do 25 Prêmio de Inovação 
**Dado que** sou pessoa curiosa e interessada em Inovação  
**Quando** sei da realização do Prêmio  
**Então** posso acompanhar sua transmissão e torcer pelo FeliciLab

## Observações
Apresentação:
https://docs.google.com/presentation/d/19XrYsxy6EB_znmwL25yZ1G_j7oU_17YPo0ZSWu0nfwQ/edit#slide=id.ge8020ed4d8_0_170
Cerimônia do prêmio anterior:
https://www.youtube.com/watch?v=fw3NTPLAkYw&t=3350s
Site do prêmio:
https://inovacao.enap.gov.br/

Importante - Guia de apresentação para os finalistas: https://drive.google.com/file/d/1TTUVK89XZAIwOAwddk9ebpmGf8mniwqC/view?usp=sharing

**Comment by RaniGub** [comment]
@pauloamoreira na daily de hoje fiz alguns direcionamentos com a @Clarisse1983, alterei a priorização dos Cards temporariamente. Vamos alinhar. A apresentação citada deve ficar no formato estilo iSUS Beiber, aqui a apresentação do iSUS
https://docs.google.com/presentation/d/1WOtN6tj8QX9jzbOJeAKakEi32z-a7vsm7dqk-hnIFfU/edit

**Comment by saracafe** [comment]
Fazendo texto: https://docs.google.com/document/d/1QE-MTOn4uO7zYRgjpsW-t6pQ2c_jpquyK3Kxc2K1BmM/edit?usp=sharing

**Comment by pauloamoreira** [comment]
@Clarisse1983, @uira, @geniltonfaheinajr como a reunião de refinamento que estava programada para o dia 31/08 e depois adiada para do dia 01/09 acabou não acontecendo, fico no aguardo de nova data ou da disponibilização das informações refinadas que serão inseridas nos novos slides. destaco que a apresentação atual está com 46 slides, então é preciso definir quais são as informações que irão compor a nova apresentação.

**Comment by pauloamoreira** [comment]
@Clarisse1983 @uira e @geniltonfaheinajr o Guia de Apresentação do evento (disponível nas Observações dessa tarefa) já aponta uma estrutura de roteiro. o texto produzido precisa seguir essa orientação.

**Comment by saracafe** [comment]
Release: https://docs.google.com/document/d/1QE-MTOn4uO7zYRgjpsW-t6pQ2c_jpquyK3Kxc2K1BmM/edit?usp=sharing

**Comment by geniltonfaheinajr** [comment]
As apresentações de todas as 18 iniciativas finalistas do 25º Concurso Inovação acontecerão no dia 16/09/2021, quinta-feira, das 14h30 às 17h00, de forma simultânea, em três salas distintas do Zoom. 

Cada sala do zoom ficará responsável pela transmissão de uma categoria do Concurso. 
Tenha em mente que as salas estarão sujeitas a lotação, portanto, aconselhamos que entre com antecedência na sala da categoria escolhida.
Após o término do prazo de resposta a este formulário, você receberá um e-mail com o link da sala virtual.

**Comment by pauloamoreira** [comment]
@uira @Clarisse1983 @geniltonfaheinajr segue link para a 1ª versão do template. nas páginas onde serão introduzidos os conteúdos que vocês irão definir incluí comentários com as orientações do Guia de Apresentações dos finalistas: [](https://docs.google.com/presentation/d/1Rtdr6U1PVpN0f51aUa17Pr8AvmbosaIwvpHXMA9mzzo/edit?usp=sharing)

**Comment by pauloamoreira** [comment]
@uira, @Clarisse1983  e @geniltonfaheinajr estou trabalhando em uma nova versão do texto guia, a partir dos apontamentos enviados para mim pelo uirá: https://docs.google.com/document/d/1ekfepQU2NKwBdTztj3i73pZohsNjOvGi1BukzoGPsoQ/edit?usp=sharing

**Comment by geniltonfaheinajr** [comment]
@pauloamoreira Paulo, aqui diz que o doc foi excluído

**Comment by RaniGub** [comment]
@geniltonfaheinajr o @pauloamoreira @uira e @wforte88 estão trabalhando na formatação do conteúdo dos slides. Achamos por bem, que o link do texto não fosse público por enquanto, então sugeri que fosse criado um grupo temporário para que não hajam desencontros entre as informações e que o Paulo seja atualizado quando o conteúdo for fechado.

**Comment by uira** [comment]
@pauloamoreira vendo agora, ficou muito boa essa edição, vamos guardar, pro livro ;)

**Comment by geniltonfaheinajr** [comment]
Segue o link de acesso à sala virtual das iniciativas finalistas da Categoria 3:  Inovação em serviços ou políticas públicas no Poder Executivo estadual, do Distrito Federal e municipal.

Dia: 16/09/2021
Horário: 14h30
Link de acesso: https://enap-gov-br.zoom.us/j/98922631012?pwd=OTMwTjRFVXN5UVAvbjRPUkordUlYUT09
ID da reunião: 989 2263 1012
Senha de acesso: 803815

As apresentações acontecerão em ordem alfabética, conforme abaixo:

1. FeliciLab- Inovação com efetividade e criatividade- Escola de Saúde Pública do Ceará Paulo Marcelo Martins Rodrigues

2. Implementação do Serviço de Telecuidado Farmacêutico - Secretaria de Estado da Saúde do Rio Grande do Sul 

3. Monitora Saúde - Agência Municipal de Tecnologia da Informação e Inovação de Campo Grande

4. Quero Impactar - Prefeitura Municipal de Recife

5. Segurança alimentar em tempos de pandemia: o caso de Belo Horizonte - Prefeitura Municipal de Belo Horizonte

6. Sistema de monitoramento e análise de organizações criminosas - Secretaria de Estado da Segurança Pública de Goiás

Até logo mais!


Comitê Gestor do Concurso Inovação

Coordenação Geral de Inovação

Concurso Inovação no Setor Público
