### ISSUE TITLE
Divulgar nova alocação de pessoas nos projetos/produtos

### ISSUE THREAD

**Issue by Clarisse1983** [EscolaDeSaudePublica/FeliciLab#190]
## **Objetivo**

**Como** pessoa colaboradora do FeliciLab
**Quero** receber o comunicado sobre a nova alocação de pessoas nos projetos/produtos
**Para** tomar conhecimento dessa novidade

## **Contexto**

- Novas dinâmicas de alocação estão acontecendo nos times dos projetos/produtos do FeliciLab, e é importante relatar isso para todes ficarem sabendo e acompanharem esses fluxos. Para que as alocações aconteçam, Uirá e Alice estão conversando com as pessoas e tomando as decisões conjuntamente. A previsão para sabermos desse novo cenário é sexta-feira, dia 3 de setembro. Pessoa de referência para fechar esse informe: Uirá. O encaminhamento é fazer um texto e colocar no nosso site, e divulgar o link como nota do Cuida da semana que vem.

## **PubliciLab**

- [x] Divulgar no Cuida, com o link
- [x] Verificar como está a estrutura do site no referente aos times e perfis de pessoas, porque isso também precisa ser atualizado

## **Critérios de Aceitação**

- [x] Visualizar informações sobre nova alocação de pessoas
**Dado que** sou pessoa colaboradora do FeliciLab  
**Quando** vejo a nota sobre a nova alocação  
**Então** fico por dentro do novo cenário

## Observações
Links de apoio e informações adicionais

**Comment by saracafe** [comment]
Hoje falei com o Uirá a respeito dessa atividade e por enquanto ainda não rolou.
