### ISSUE TITLE
Elaborar convite para o Concurso de Inovação

### ISSUE THREAD

**Issue by saracafe** [EscolaDeSaudePublica/FeliciLab#196]
## **Objetivo**

**Como** pessoa parceria do Felicilab
**Quero** enviar convite
**Para** assistir prêmio de inovação

## **Contexto**

A apresentação do concurso de inovação da Enap será apresentado nessa quinta-feira (16) É preciso enviar um texto por email e por telegram/whatsapp para aos parceiros do FeliciLab convidando para assistir a apresentação.  

## **PubliciLab**

- [x] Fazer convite para Professor Paulo Henrique Mendes phmendes@gmail.com (85) 99955.7181
- [x] Enviar para os contatos do Thoughtworks que o Genilton passou por telegram
- [x] Enviar o link da apresentação aos parceiros

## **Critérios de Aceitação**

- [x] Comparecer a apresentação do prêmio de inovação
**Dado que** sou parceiro do FeliciLab
**Quando** recebo o convite do evento
**então** assisto a apresentação

## Observações
Links de apoio e informações adicionais

**Comment by saracafe** [comment]
https://docs.google.com/document/d/1AqFSUDyEH8xqhyHIpcQtRTXNVsVfL32MAQuex6ewqCQ/edit?usp=sharing

**Comment by saracafe** [comment]
Foi enviado email e no whatsapp convidando os parceiros para participar do evento. Na quinta-feira é preciso enviar o link para entrar na sala

**Comment by geniltonfaheinajr** [comment]
Os links para acessar a sala serão enviados amanhã pela manhã. Conforme email recebido hoje pela coordenação do evento.
