### ISSUE TITLE
Criar minibio, fotos e dados dos eventos da ESP na Semana de Inovação

### ISSUE THREAD

**Issue by saracafe** [EscolaDeSaudePublica/FeliciLab#204]
## **Objetivo**

**Como** pessoa comunicadora da inovação da ESP  
**Quero** criar minibio e dados dos eventos  
**Para** participar da semana de inovação

## **Contexto**

- A Semana da Inovação ocorrerá em outubro e durante essa semana tivemos alguns reuniões de alinhamentos com a Beatriz do NIT Uece. Temos alguns encaminhamentos.

## **PubliciLab**

- [x] Perguntar Beatriz sobre o formato das artes (@saracafe)
- [x] Até dia 22, entregar minibios com fotos, come completo e dados do evento. Colocar na pasta com as outras bios disponibilizadas pelas instituições parceiras (@saracafe)
- [x] Até dia 22, fazer textos para o Sympla (@saracafe) 
- [x] Fazer um resumo colocando nome do evento, dia, hora, nome da pessoa e minibio para facilitar o trabalho do designer (@saracafe)
- [x] Até 22/09 entregar as artes referentes aos eventos da ESP (@danielgula)
- [x] Conferir se está tudo certo com Genilton
- [x] @danielgula alterar a foto do card da Fotini Toscas
- [x] Revisão final @geniltonfaheinajr 

## **Critérios de Aceitação**

- [x] Faço as artes referente aos eventos da ESP
**Dado que** sou pessoa comunicadora da inovação da ESP
**Quando** faço as artes
**então** entrego o material e participo da semana

## Observações
https://drive.google.com/drive/u/0/folders/1k1v2cbS3DQj6jcL-uTLugreyQSIWUhKI

**Comment by saracafe** [comment]
Minibio dos participantes: https://drive.google.com/drive/folders/1siJgdkST3n7fWtyzT2KJ8NOTNaPksD0Z

Textos para o Sympla: https://docs.google.com/document/d/1CnwfdJlPJGZj3lV3KNUYECHw7f5EFwX6gjm_6P7hACY/edit?usp=sharing

**Comment by saracafe** [comment]
Briefing: https://docs.google.com/document/d/1l_kfojFeiLAFdE7tjdV5IGCnSTLJc-VPwAeVVfogXmE/edit?usp=sharing (@danielgula)

**Comment by saracafe** [comment]
Briefing: https://docs.google.com/document/d/1l_kfojFeiLAFdE7tjdV5IGCnSTLJc-VPwAeVVfogXmE/edit?usp=sharing 

Fotos: https://drive.google.com/drive/folders/1GtQXgMGD6DRf9yLzw_u2qIuhA_G-Ha6j

Agora vai @danielgula

**Comment by danielgula** [comment]
Todas as 20 imagens (Instagram e Stories) mais a tela de fundo do Stream Yard, mais A imgem do evento Sympla estão disponíveis na pasta compartilhada da Semana > Palestrantes > DIT

**Comment by geniltonfaheinajr** [comment]
Ok. Artes conferidas.
Vou conferir as infos das artes e confirmar as datas com os e-mails que foram enviados. Encontrei erros no cronograma que o NIT/UECE organizou. Há informações duplicadas.

**Comment by geniltonfaheinajr** [comment]
E-mails verificados. @Clarisse1983 verificar as informações repassadas para as Fotini e Gabriela e parear com as que estão nas artes. Não foi enviado e-mail para elas duas. Sugiro deixar o card aberto até o retorno da Clarisse.

**Comment by geniltonfaheinajr** [comment]
@danielgula Alterar a imagem do card da Fotini Toscas https://drive.google.com/file/d/1T9oPZQQCpSEDsr-lwdWNKVLUKSPVuMhC/view?usp=sharing

Para esta foto:
https://drive.google.com/file/d/12RasMt0Svlp8W0GWhzUi_yNjwTJNrGVa/view?usp=sharing

**Comment by danielgula** [comment]
@geniltonfaheinajr alterações de fotos feitas e publicadas na pasta.
