### ISSUE TITLE
Criar design system das soluções digitais em educação

### ISSUE THREAD

**Issue by Clarisse1983** [EscolaDeSaudePublica/FeliciLab#21]
As soluções de educação permanente estão sendo criadas com identidades visuais muitos distintas, e quando colocados lado a lado nem parece que são partes de uma mesma estratégia integrada. Portanto é preciso que se crie o design system do FeliciLab, apontando fontes, grafismos, cores, e todo o conjunto de elementos visuais ao qual seja possível recorrer na criação de aplicações para nossos produtos.

**Comment by danielgula** [comment]
O @RaniGub está coordenando esse projeto dentro do board do Designlab, que junto ao Publicilab montará as estratégias para atender essa demanda. Portanto, ela será fechada deste board.
