### ISSUE TITLE
Produzir StreamYeard dos eventos da ESP na Semana de Inovação

### ISSUE THREAD

**Issue by ClarisCaval** [EscolaDeSaudePublica/FeliciLab#221]
## **Objetivo**

**Como** pessoa da organização da Semana de Inovação responsável pelo apoio à transmissão
**Quero** organizar o passo a passo para a realização da transmissão
**Para** que tudo dê certo e o evento seja um sucesso

## **Contexto**

- A Semana de Inovação ocorrerá de 18 a 22 de outubro, e esse card é específico para as ações de apoio à realização da transmissão de todos os nossos eventos (promovidos pela ESP), com uso da plataforma StreamYeard. Daniel será o responsável, com apoio da Ana Paula, pela operacionalização dessa frente de trabalho.

## **Escopo**

- [x] Obter login e senha do StreamYard da Secitece, que será utilizado nas transmissões;
- [x] Revisar documento de orientação a ser encaminhado a todos os participantes das mesas;
- [x] Encaminhar documento de orientação a todos os participantes das mesas, com link de entrada para o evento;
- [x] Operacionalizar a transmissão

## **Critérios de Aceitação**

- [x] Transmitir eventos da ESP na Semana de Inovação
**Dado que** somos uma instituição participante da promoção da Semana Estadual de Inovação  
**Quando** realizo o evento com uso do StreamYeard  
**Então** transmito os eventos pelo canal do YouTube da Escola

## Observações
Links de apoio e informações adicionais

**Comment by anapvcv** [comment]
A partir da reunião que tivemos hoje (15/10), foi acordado que não será mais preciso manejar as lives, porque essa atividade será de responsabilidade da SECITECE. Pediu-se também apoio na divulgação, porque só tem 600 inscritos. 

Precisamos entrar em contato com a Ariane para conseguir a chave de transmissão do Youtube da ESP e saber se é possível que alguém fique no chat para disponibilizar os formulários dos certificados. O @danielgula vai combinar com ela. 

A @saracafe vai disparar as mensagens de confirmação, através do Sympla, antes de cada evento.  https://docs.google.com/document/d/1D4W9ggFdoBSUouYJbUsWnn6nxc9ySWbp/edit 

E eu vou entrar em contato com os participantes, disponibilizando as instruções para o acesso ao Stremyard. https://drive.google.com/drive/folders/17WR2NviHfOJthXnr5P-pekzCgnFJzW8W 

Também foi divulgado uma sugestão de cerimônia para os mediadores. Olha só, @Clarisse1983 e @uira! https://docs.google.com/document/d/1OOq4avrLbeEvWE3beS8sQYVNKMIh9Ps9/edit
