### ISSUE TITLE
Divulgar participação na Semana Nacional de Inovação 2021

### ISSUE THREAD

**Issue by anapvcv** [EscolaDeSaudePublica/FeliciLab#223]
## **Objetivo**

**Como** pessoa comunicadora do Felicilab
**Quero** divulgar a participação do Laboratório na Semana Nacional de Inovação
**Para** expandir o acesso às informações do Laboratório

## **Contexto**

- A Semana de Inovação 2021 vai ocorrer de 9 a 12 de novembro e visa fomentar a discussão de ideias, a troca de experiências e uma mentalidade mais disruptiva na Administração Pública. Além disso, favorece e dissemina a cultura da inovação entre os agentes públicos e apresenta tendências e possibilidades para a transformação das organizações. 

## **Escopo**

- [x] Divulgar Semana de Inovação [datas, nome da nossa atividade, inscrições]
- [x] Divulgar a nossa participação no prêmio da ENAP e data do resultado através do vídeo.

## **Critérios de Aceitação**

- [ ] titulo  
**Dado que** quero divulgar as atividades em que o Felicilab participa 
**Quando** entro em contato com a Ascom
**então** articulo a veiculação dessas informações 

## Observações
Links de apoio e informações adicionais

**Comment by Clarisse1983** [comment]
@anapvcv vai checar se as inscrições para nossa atividade estão disponíveis e verificar sobre a divulgação com a Ascom.

**Comment by Clarisse1983** [comment]
Para finalizar a tarefa, manda um email para a Ascom, @anapvcv, solicitando a cobertura do dia 12 ;)
