### ISSUE TITLE
[Edição 2] Produzir ReuniãoZona

### ISSUE THREAD

**Issue by saracafe** [EscolaDeSaudePublica/FeliciLab#228]
## **Objetivo**

**Como** pessoa colaboradora do DIT/FeliciLab 
**Quero** me programar para a edição 2 da Reuniãozona
**Para** participar presencialmente do mesmo

## **Contexto**

- A Reuniãozona é um momento de encontro presencial geral com todo o time, para atualização e diálogo sobre os processos de trabalho em curso, principais informes, etc. A primeira edição dessa nova versão ocorreu em 4 de outubro. O segundo encontro será dia 12 de novembro, com a presença de Washington Forte.

## **PubliciLab**

- [x] Criar agenda
- [x] Atualizar arte (data e hora)
- [ ] Fazer release sobre a programação
- [ ] Enviar release à Ascom e solicitar divulgação e cobertura do evento
- [x] Mobilizar pessoas (divulgação no Telegram, envio de email e mobilização por telefone - Nicolas)
- [ ] Fazer a cobertura para blog e insta
- [ ] Fazer teaser do evento para divulgação posterior

## **Critérios de Aceitação**

- [x] Participar da ReuniãoZona
**Dado que** sou pessoa colaboradora do DIT/FeliciLab 
**Quando** sou mobilizada a participar do evento  
**Então** me faço presente

## Observações
Links de apoio e informações adicionais

**Comment by Clarisse1983** [comment]
Na página de Contato, ajustar:
- retirar esse subtítulo 'transversalidade...'
- retirar esse mapa
- inserir o texto revisado no doc que Sara linkou acima.

**Comment by saracafe** [comment]
Levantamento dos post it no NIT em Transformação https://docs.google.com/document/d/13ttJS9b3p_ZhEFof8YLrmqkHFugA_BdXkDCFlB5Uocg/edit?usp=sharing

**Comment by geniltonfaheinajr** [comment]
Fazer convite para a TW (Renata Gusmão e Gisele Burk) e professor Paulo Henrique da UECE.

**Comment by danielgula** [comment]
Segue artes atualizadas (convite e PPT
![convite1](https://user-images.githubusercontent.com/39468037/141389884-f88e857d-a34a-41a4-b94d-0050511a0591.jpg)
![ppt](https://user-images.githubusercontent.com/39468037/141389885-d6386595-88f2-492e-b4a0-eb06fedb2b9a.jpg)
)

**Comment by Clarisse1983** [comment]
A ReuniãoZONA aconteceu das 14h às 17h, no Auditório Pontes Neto, onde fizemos informes e também uma dinâmica de mitigação das dores e avaliação das expectativas.
