### ISSUE TITLE
Revisão dos conteúdos do site Felicilab v2.0 emergencial

### ISSUE THREAD

**Issue by danielgula** [EscolaDeSaudePublica/FeliciLab#230]
## **Objetivo**

**Como** internauta
**Quero** acessar o site do Felicilab
**Para** ver a informações corretas de pessoas, times e soluções

## **Contexto**

O site do Felicilab possui novas páginas que precisam ser revisadas antes da publicação final

## **Escopo**

- [x] Revisar página de Contato
- [x] Revisar página Quem Somos
- [x] Revisar página Soluções
- [x] Verificar títulos de cada solução

## **Critérios de Aceitação**

**Dado que** estou na Internet
**Quando** acesso o site Felicilab
**então** vejo os conteúdos revisados

## Observações
Links de apoio e informações adicionais:
https://sus.ce.gov.br/felicilab/contato/
https://sus.ce.gov.br/felicilab/solucoes/
https://sus.ce.gov.br/felicilab/quem-somos/

**Comment by saracafe** [comment]
https://docs.google.com/document/d/1x6nDmbOS22Dlj3Op-7z5FPMq5FesLwupeBOrkPZ4EBk/edit?usp=sharing

**Comment by Clarisse1983** [comment]
Na página de Contato, ajustar:

retirar esse subtítulo 'transversalidade...'
retirar esse mapa
inserir o texto revisado no doc que Sara linkou acima.

**Comment by danielgula** [comment]
Sobre os títulos de cada programas e as descrições na página [Soluções], tudo certo? Já está no ar.

**Comment by Clarisse1983** [comment]
Na página quem somos, alguns detalhes:
 - Perfil Laysa, inserir o perfil no Mapa: https://mapa.sus.ce.gov.br/agente/51/
