### ISSUE TITLE
Apoiar a realização da Oficina de Design de Serviços para o público interno da ESP

### ISSUE THREAD

**Issue by anapvcv** [EscolaDeSaudePublica/FeliciLab#231]
## **Objetivo**

**Como** integrante do Time de Narrativas
**Quero** apoiar a realização da Oficina de Design de Serviços para o público interno da ESP
**Para** que a ação seja bem divulgada dentro da Escola.

## **Contexto**

- O Laboratório de Inovação da Escola de Saúde Pública do Ceará - FeliciLab pretende promover nos dias 1, 2 e 3 de dezembro de 2021, a Oficina de Design de Serviços Públicos direcionada à aplicação das metodologias de Design Thinking na organização, planejamento e execução das atividades realizadas pelos diversos setores da Escola. 

## **Pré-produção**

- [x] Produzir release
- [x] Criação de Grupo de WhatsApp
- [x] Programação 
- [ ] Divulgação / Apoio na mobilização de participantes
- [x] Ficha de inscrição
- [x] Articular divulgação das inscrições com a Ascom

## **Produção**

- [x] Realizar registro audiovisual
- [x] Realizar registro fotográfico
- [x] Articular cobertura com a Ascom

## **Pós-Produção**
- [x] Aplicação do formulário de Feedback
- [x] Relatório de Feedback
- [x] Ladding Page
- [x] Programação - Felicilab

## Observações
Links de apoio e informações adicionais
https://docs.google.com/document/d/1Xqjr1KejwOvVsG--3CRSn7aT9Rd3mYVcuFA3UI4u0ds/edit

**Comment by saracafe** [comment]
Release Oficina de Design de Serviços na Sepos: https://docs.google.com/document/d/1bLMOdGmRNK3kw3m4g2AlwKEfrjpO2T2ykOqBCc5WDiU/edit?usp=sharing

**Comment by pauloamoreira** [comment]
.tarefa encerrada por todo escopo ter sido realizado, documentado em épico correspondente.
