### ISSUE TITLE
Exposição para a ReuniãoZona

### ISSUE THREAD

**Issue by raiannyqz** [EscolaDeSaudePublica/FeliciLab#237]
## **Objetivo**

**Como** participante do Publicilab
**Quero** organizar a Exposição da ReuniãoZONA  
**Para** mostra coletiva dos colaboradores Felicilab

## **Contexto**

- Como última reuniãoZONA do ano, momento de atualização das informações e também de confraternização realizaremos uma exposição, como mostra coletiva dos colaboradores Felicilab.

## **Escopo**

- [x] FAZER PROPOSTA PARA APROVAÇÃO DA MOSTRA
- [x] REVISÃO TEXTUAL
- [x] ENVIADO PARA APROVAÇÃO

1.	Pré-Produção
- [x] Nome: MOSTRA NAVEGANTES INOVADORES ESP
- [x] Ida ao Nugad falar sobre infraestrutura e materiais para solicitação
- [x] Memo solicitando a disponibilidade dos materiais (Nicolas)
- [x] Visita a sala do anexo para ver o espaço disponível para a exposição
- [x] Escrever uma nota de mobilização para as pessoas trazerem seus materiais para exposição
- [x] Recebimento dos material físico e digital 
- [x] Organização do material recebido
- [x] Expografia
- [x] Levantar material para produção

2.	Produção
- [x] Montagem
- [x] Making-of

3.	Pós-produção
- [x] Desmontagem
- [x] Material devolvido no mesmo dia

## Observações
https://docs.google.com/document/d/1rGxOx8_dZsWK2maHZAthLCMSMpFSLZh5/edit
https://docs.google.com/spreadsheets/d/1X-P5C9ooDSmeh17YS6qScXDFpvIT1_acpRGsqU6-YE8/edit#gid=0
https://docs.google.com/document/d/1Df8UcJSJ6ruL_DUWkNyunpFsoNsr9sJKs-u5Ze_yNZA/edit

**Comment by raiannyqz** [comment]
Segue PROPOSTA MOSTRA ESP @Clarisse1983 @saracafe 
[PROPOSTA MOSTRA ESP.docx](https://github.com/EscolaDeSaudePublica/FeliciLab/files/7559099/PROPOSTA.MOSTRA.ESP.docx)

Por favor deem uma olhada na proposta @saracafe fique a vontade para os melhoramentos textuais e @Clarisse1983 por favor me repassa os apontamentos e/ou melhoramentos textuais. Para que se for possível possamos repassar para aprovação ou não da proposta. Já agradeço!!

**Comment by Clarisse1983** [comment]
@raiannyqz oie, coloca como documento do Google, aberto, e salva na nossa pasta do PubliciLab no drive. Sara pode te ajudar.

**Comment by raiannyqz** [comment]
> @raiannyqz oie, coloca como documento do Google, aberto, e salva na nossa pasta do PubliciLab no drive. Sara pode te ajudar.
Certo @Clarisse1983 , está na pasta @saracafe :

https://drive.google.com/drive/folders/1Dph3Ub34Jd2dowzEZzr-jsrTQV95val4

**Comment by RaniGub** [comment]
Bom dia @raiannyqz, tudo bem? Esta tarefa deve tramitar pela board do Publicilab. Vou remover do DesignLab.

**Comment by raiannyqz** [comment]
> Bom dia @raiannyqz, tudo bem? Esta tarefa deve tramitar pela board do Publicilab. Vou remover do DesignLab.

Bom dia! Ahhh Tudo certo!

**Comment by raiannyqz** [comment]
Olá @saracafe como está revisão? Foi repassado para Clarisse a sua versão?

**Comment by saracafe** [comment]
> Olá @saracafe como está revisão? Foi repassado para Clarisse a sua versão?

Fiz algumas sugestões no texto: https://docs.google.com/document/d/1rGxOx8_dZsWK2maHZAthLCMSMpFSLZh5/edit?usp=sharing&ouid=101447433007826342335&rtpof=true&sd=true

**Comment by raiannyqz** [comment]
Hoje Eu e @Clarisse1983 propomos a ideia da exposição ao RH e aguardamos marcar reunião para apresentar a proposta.

**Comment by Clarisse1983** [comment]
Fazer contato com a Lucinha, do NUGAD, para ver materiais disponíveis. E conhecer a sala, para pensar na estrutura da exposição para nossa galera. A ESP não realizou ainda a reunião com a Comissão de Eventos.

**Comment by raiannyqz** [comment]
@saracafe olá Sara, você teria como fazer esta nota?:
Escrever uma nota de mobilização para as pessoas trazerem seus materiais para exposição

**Comment by raiannyqz** [comment]
Ontem foi realizada a reunião de Natal da ESP, contudo não será possivel efetuar a mostra com toda a ESP diante do tempo que temos, pois na proposta, inicialmente, o cronograma constava um mês de execução. Então resolvemos fazer uma mostra interna do felicilab que será no dia e horário da reuniãoZONA.

**Comment by raiannyqz** [comment]
Para as próximas etapas iremos informar aos felicilabs sobre a mostra individualmente, para entender como cada um irá apresentar e como irá apresentar, vendo as necessidades e materiais que podemos auxiliar.

**Comment by saracafe** [comment]
> @saracafe olá Sara, você teria como fazer esta nota ?: Escrever uma nota de mobilização para as pessoas trazerem seus materiais para exposição

Ei turma criativa! Nossa reuniãoZona está se aproximando e para deixar o nosso dia mais interativo, vamos contar com a Mostra Navegantes Inovadores DIT/FeliciLab! 

Se você tem algum talento, quer fazer uma oficina, performance ou tem uma veia cômica… você pode se apresentar no nosso último encontro do ano! 

Estamos convocando o time para compartilhar suas habilidades conosco e assim, fazermos uma grande festa no dia 17/12! 

Tem interesse? Fala com a Raianny para entendermos como será a sua apresentação e como podemos te auxiliar.

Bora nessa?

**Comment by raiannyqz** [comment]
@Clarisse1983  @saracafe  precisamos definir sobre a entrega dos trabalhos, se especificarmos que será até o dia 16, precisamos de um espaço para guardar estes trabalhos até o dia da montagem. E se dissermos que será até o dia 17, temos que definir um horario maximo de entrega tipo até as 10:00 hs, pra que possa dá tempo de montar.

**Comment by raiannyqz** [comment]
Lista de Trabalhos para mostra: https://docs.google.com/spreadsheets/d/1X-P5C9ooDSmeh17YS6qScXDFpvIT1_acpRGsqU6-YE8/edit#gid=0

**Comment by Clarisse1983** [comment]
Que a Gabriela estava se revelando como ótima gestora de projetos, todo mundo já tava se ligando. Mas que ela manjava no crochê, quem sabia? E nossa rainha de dados, Camila, que faz drinks e capuchino caseiro como ninguém? Ah, e o povo de exatas também gosta de miçangas, Janete que o diga!

Para revelar esses múltiplos talentos de nosso time diverso, vamos realizar a 1ª Mostra Navegantes Inovadores DIT/FeliciLab, no dia 17 de dezembro, durante nossa última ReuniãoZona, das 14h às 17h. Teremos tanto exposição assíncrona de nossas obras de arte, quanto intervenções em tempo real, ao vivo e a cores, nos intervalos da reunião.

Então se você tem algum talento, se performa nas receitinhas ou nas pinturas e quer mostrar como faz ou o que já fez… deixe sua estrela brilhar no nosso último encontro do ano! É só nos dizer oque precisa para expor seus materiais/gestuais, trazer tudo até o dia 16 e entregar à Raianny, e pronto, só receber os aplausos!

1ª Mostra Navegantes Inovadores
Sexta-feira, 17 de dezembro
Das 14h às 17h
Sala 2 do Anexo - Vizinho ao Posto de Saúde

**Comment by Clarisse1983** [comment]
@saracafe vai enviar um lembrete hoje no grupão, pra agitar o povo.

**Comment by raiannyqz** [comment]
Etiquetas para impressão da exposição: https://docs.google.com/document/d/1n218L9fpgiJf4BGxBC37JWGSOssUdl3OPUgCpTJTsk8/edit
