### ISSUE TITLE
Ajuste de contato de email do Publicilab

### ISSUE THREAD

**Issue by danielgula** [EscolaDeSaudePublica/FeliciLab#239]
## **Objetivo**

**Como** usuário
**Quero** entrar em contato com o Publicilab
**Para** interagir com a inovação em saúde

## **Contexto**

Com a criação do nosso email institucional, precisamos corrigir algumas informações do contato para gerenciar melhor o fluxo de atendimento das pessoas.

## **Escopo**

- [x] alterar o alias "lab" do email para "Publicilab", via chamado do GTEC
- [ ] criar assinatura de email padrão

## **Fora de Escopo**

- Criar uma mensagem padrão

## **Critérios de Aceitação**

**Dado que** sou cliente publicilab
**Quando** interajo via email
**então** tenho uma comunicação mais clara

**Comment by raiannyqz** [comment]
O chamado foi criado: ESPCE#: 20211119585115

**Comment by Clarisse1983** [comment]
Jardson resolveu usando Publicilab, que já aparece como assinatura.

**Comment by raiannyqz** [comment]
O nome Lab foi modificado para Publicilab ESP/CE
![pasted-1637591628-856188](https://user-images.githubusercontent.com/28989404/143018273-abf06b8b-2395-4045-a5d9-e5cfa2a9740d.png)

**Comment by raiannyqz** [comment]
@Clarisse1983  Olá Clarisse o nome foi alterado, como na imagem inserida:
![Publicilab ESP-CE](https://user-images.githubusercontent.com/28989404/143018652-070721bf-8fd4-4658-a843-8f3dda3bfcaa.JPG)

**Comment by raiannyqz** [comment]
@Clarisse1983 Olá Clarisse o nome foi alterado, como na imagem inserida:
Está tudo certo? Se nao estiver, peço alteração.
![Publicilab ESP-CE](https://user-images.githubusercontent.com/28989404/143018867-61be03df-c536-49ff-93f0-ae8f19303b92.JPG)

**Comment by Clarisse1983** [comment]
Sim, tudo certo. ;)

*Clarisse Castro Cavalcante*
Jornalista pela Universidade Federal do Piauí.
Especialista em Teorias da Comunicação e da Imagem pela Universidade
Federal do Ceará.
Mestre e Doutora em Informação e Comunicação em Saúde pela Fundação Oswaldo
Cruz (RJ).
85.981116986





Em ter., 23 de nov. de 2021 às 08:48, Raianny Queiroz <
***@***.***> escreveu:

**Comment by Clarisse1983** [comment]
Qual a assinatura que vcs propuseram, gente?

**Comment by Clarisse1983** [comment]
Fazer proposta a partir da descrição:
Pensar e executar as estratégias de comunicação do FeliciLab são as principais atribuições do PubliciLab. Aqui usamos as metodologias ágeis para organizar, acompanhar e executar desde ações mais operacionais, como produção de conteúdos específicos para nossas plataformas de comunicação, quanto ações mais políticas, como articulação com comunidades de práticas, dentro das redes, com o intuito de fomentar beleza, criatividade e diálogo entre pessoas e iniciativas que estão transformando o mundo pela inovação. 

Em sintonia especial com o DesignLab e os demais labs, e também com a Assessoria de Comunicação da Escola de Saúde Pública do Ceará, investimos em criação e publicização com transparência e colaboração.

**Comment by raiannyqz** [comment]
​Atenciosamente,
Publicilab - estratégias e comunicação do
Felicilab - Laboratório de Inovação da
ESP/CE - Escola de Saúde Pública do Ceará
E-mail: publicilab@esp.ce.gov.br
Web: https://sus.ce.gov.br/felicilab/publicilab/
Governo do Estado do Ceará
--

**Comment by raiannyqz** [comment]
Fiz um chamado para o SUPORTE ESPCE#: 20211124585144 para que eles pudessem me informar como eu poderia criar uma assinatura para o email. Eles me responderam que eu teria fazer o chamado para ASCON
<img width="358" alt="Captura de tela 2021-11-24 164340" src="https://user-images.githubusercontent.com/28989404/143303861-c6f8e938-79ec-464e-8da0-df5da614f2a2.png">

**Comment by Clarisse1983** [comment]
Publicilab - Narrativas e Conteúdos de Inovação em Saúde.

**Comment by raiannyqz** [comment]
> Atenciosamente,
> 
> Publicilab - Narrativas e Conteúdos de Inovação em Saúde.

Foi realizado um chamado para a ASCON ESPCE#: 20211129585161

**Comment by danielgula** [comment]
Passando pelo board e vi esse card. Me parece que ele foi concluído e pode ser encerrado.

**Comment by raiannyqz** [comment]
Hoje enviei mensagem pela central de atendimento sobre a demanda da assinatura que continua sem resposta:
![assinatura email](https://user-images.githubusercontent.com/28989404/146986970-9aca883d-ef14-4d64-8ba9-5d0c18dfbdd2.png)
a

**Comment by raiannyqz** [comment]
Esta tarefa está bloqueada, pois ainda não temos respostada ASCOM.
