### ISSUE TITLE
[11/02/21] Planejamento das estratégias de comunicação digital do FeliciLab

### ISSUE THREAD

**Issue by saracafe** [EscolaDeSaudePublica/FeliciLab#24]
https://docs.google.com/document/d/1kGGxV-2UvEif8AZ5pWaNfPP3Iofh-Qw0jrKjrsOQzuI/edit#heading=h.y4ndaei53jef

Reunião presencial terça-feira (09/02), de 09h as 12h

**Comment by Clarisse1983** [comment]
Tivemos reunião ontem e teremos outra amanhã, 11/02, para ouvir as contribuições do Washington e fechar o documento.
