### ISSUE TITLE
Criar certificado da Semana da Inovação do Ceará

### ISSUE THREAD

**Issue by saracafe** [EscolaDeSaudePublica/FeliciLab#241]
## **Objetivo**

**Como** pessoa participante da Semana da Inovação do Ceará  
**Quero** receber certificado  
**Para** confirmar presença na Semana da Inovação do Ceará 

## **Contexto**

- As ICTs cearenses produziram a 1º Semana da Inovação do Ceará que ocorreu de 18 a 22 de outubro de 2021. É preciso fazer os certificados para as pessoas participantes, moderadoras, palestrantes e organizadoras. 

## **PubliciLab**

- [x] Fazer a arte dos certificados
- [x] Colocar os nomes das pessoas participantes
- [x] Enviar os certificados modelos para as outras instituições
- [x] Revisar certificados

## **Critérios de Aceitação**

- [ ] Receber os certificados
**Dado que** participei da Semana da Inovação 
**Quando** recebo o certificado 
**então** comprovo presença no evento

## Observações
Links de apoio e informações adicionais

**Comment by saracafe** [comment]
Produção dos certificados https://drive.google.com/drive/folders/1eoNuFVeiAPgRD8NzJRam9c9nMLqzdddL

**Comment by raiannyqz** [comment]
As artes foram feitas, os nomes dos participantes já estão sendo inseridos.

**Comment by raiannyqz** [comment]
Foi criado uma pasta de backup dos certificados para que seja se fonte interna e não compartilhado
https://drive.google.com/drive/folders/1wAV1XsTOHiyZmIhV637wBkIeXblJngRj?usp=sharing
