### ISSUE TITLE
Briefing Edital 26

### ISSUE THREAD

**Issue by saracafe** [EscolaDeSaudePublica/FeliciLab#245]
## **Objetivo**

**Como** pessoa comunicadora da inovação
**Quero** pautar a Ascom da ESP
**Para** divulgar o Edital 26

## **Contexto**

- O Edital 26 possui 49 perfis profissionais desejados a se tornarem bolsistas das soluções digitais da ESP nos próximos 12 meses. É preciso fazer um briefing com as informações principais, montar uma narrativa e assim pautar a Ascom/ESP para fazer a divulgação do certame. 

## **Escopo**

- [x] Mapear as principais informações do Edital 26
- [x] Montar o briefing
- [x] Solicitar a Ascom a divulgação do Edital

## **Critérios de Aceitação**

**Dado que** estou procurando oportunidades de trabalho
**Quando** recebo informações da campanha do Edital 26
**então** me inscrevo no certame

## Observações
Briefing https://docs.google.com/document/d/19n6_mow5QLER287h6Mgkrdqr6IvDYSBC0U5SbCL6Xrs/edit?usp=sharing

**Comment by Clarisse1983** [comment]
Teremos reunião com Ascom na segunda-feira, 06/12, às 10h, para discutir os encaminhamentos.

**Comment by Clarisse1983** [comment]
Discutimos o briefing na reunião dessa manhã e encaminhamos o email a tarde para a Ascom.
