### ISSUE TITLE
Mapeamento dos Articuladores

### ISSUE THREAD

**Issue by raiannyqz** [EscolaDeSaudePublica/FeliciLab#246]
## **Objetivo**

**Como** pessoa comunicadora da inovação
**Quero** mapear os articuladores
**Para** divulgar o edital 26

## **Contexto**

- O Edital da ESP possui vários perfis que precisam ser listados, organizados, mapeados para contribuir na divulgação do edital.

## **Escopo**

- [x] Fazer uma busca no site do MEC dos cursos das universidades 
- [x] Listar em uma planilha esse mapeamento
- [x] Enviar para Ascon para a divulgação do Edital

## **Critérios de Aceitação**

- [x] titulo  
**Dado que** estou procurando oportunidades de trabalho nas áreas em questão do edital
**Quando** recebo informações
**então** me inscrevo

## Observações
https://docs.google.com/spreadsheets/d/1ROQSUPtxjhmvFJw4qox6QEFGZGOc6xM86SH-GO1M8pA/edit#gid=0

**Comment by raiannyqz** [comment]
Eu fiz uma busca só pela palavra design no portal do mec e veio 1262 de resultados de cursos que tem essa palavra. Ou seja, acredito que precisamos refinar nossa buscar, objetivar o nordeste por exemplo. Por que são muitos os perfis, como iriamos contactar todos estes espaços? Talvez fosse mais interessante colocar o edital nos sites que já são destinados a isso, pois eles consegem alcançar o Brasil todo, como o gran concursos. E fazer uma divulgação mais direcionada.
![e-MEC - 1 v 5 851 1-7069 - Google Chrome](https://user-images.githubusercontent.com/28989404/144439302-2162c08f-5ac8-4b38-ba78-a64230dfdc40.jpg)

**Comment by raiannyqz** [comment]
MAPEAMENTO
https://docs.google.com/spreadsheets/d/1ROQSUPtxjhmvFJw4qox6QEFGZGOc6xM86SH-GO1M8pA/edit#gid=0

**Comment by Clarisse1983** [comment]
Definir as ações com @uira 
1) Lista de transmissão
2) Reunião com pessoas mais estratégicas

**Comment by Clarisse1983** [comment]
Conversei com a Ariane sobre a lista de transmissão e ela disse que podia incluir os email que levantamos na lista da ESP, e pediu que encaminhassemos a planilha. Já enviei.

**Comment by Clarisse1983** [comment]
Vou fechar o card e se formos reunir com pessoas específicas, abro outra tarefa.
