### ISSUE TITLE
Realizar testes no Mapa da Saúde

### ISSUE THREAD

**Issue by saracafe** [EscolaDeSaudePublica/FeliciLab#247]
## **Objetivo**

**Como** pessoa comunicadora da inovação  
**Quero** testar as oportunidade no Mapa da Saúde
**Para** visualizar erros e o que pode melhorar

## **Contexto**

O Edital 26 possui 49 perfis profissionais desejados a se tornarem bolsistas das soluções digitais da ESP nos próximos 12 meses. Pela primeira vez o processo seletivo será realizado pelo Mapa da Saúde. Faremos os testes dos link para visualizar erros e o que pode melhorar

## **Escopo**

- [ ] Visitar os links
- [ ] Anotar erros e melhorias

## **Critérios de Aceitação**

- [ ] Acesso os links sem erros 
**Dado que** sou pessoa comunicadora da inovação 
**Quando** visito os links e dou feedback de melhorias  
**então** links das oportunidades sem erros

## Observações
https://mapadasaude.dev.org.br/oportunidade/337/
https://mapadasaude.dev.org.br/oportunidade/341/

**Comment by saracafe** [comment]
Alguns feedback https://docs.google.com/document/d/1vaNLTVMEwIGzv5AMIW2nkoo7tG0EKocyA7ZbvhiwdkU/edit?usp=sharing

Coloque no documento suas impressões também

**Comment by Clarisse1983** [comment]
Encaminhei os feedbacks à Thaís, por orientação dela. Ela está reunindo para fazer os encaminhamentos.
