### ISSUE TITLE
Produzir material audiovisual para a divulgação do Edital 26

### ISSUE THREAD

**Issue by anapvcv** [EscolaDeSaudePublica/FeliciLab#250]
## **Objetivo**

**Como** profissional inovador
**Quero** ter acesso ao material audiovisual da campanha
**Para** me inscrever e participar da inovação aberta em saúde
## **Contexto**

- O Edital 26 possui 49 perfis profissionais desejados a se tornarem bolsistas das soluções digitais da ESP nos próximos 12 meses. É preciso construir uma campanha que possa atingir esse público-alvo diverso, em pouco tempo, informando como essa pessoa deve se inscrever e participar do certame, garantindo assim uma grande adesão.

## **Escopo**

- [x] Reels de divulgação das áreas de atuação
- [x] Vídeo tutorial explicando o que é o Mapa Digital da Saúde e como se inscrever no Edital
- [ ] Teaser do Laboratório 

## Observações
Links de apoio e informações adicionais 

https://drive.google.com/drive/u/0/folders/1hM8YydRYxI2VETEMCQCTnlXiJzel6b-C

**Comment by anapvcv** [comment]
Os reels da Camila e do Victor estão disponíveis nesse link.  O Washington ficou tímido pra fazer. https://drive.google.com/drive/u/0/folders/1hM8YydRYxI2VETEMCQCTnlXiJzel6b-C

**Comment by Clarisse1983** [comment]
Certo, vamos lá. As imagens e áudios estão bem melhores... Embora ainda estejam caretas hehe, mas ok, considerando o contexto... Agora a gente precisa destacar algumas informações na tela, à medida que eles forem falando. Tipo, as especificidades e linguagens dos programadores que o Vitim cita (mobile, full stack - ver com ele como escreve isso), palavras-chaves na Camila, como Ciência de Dados e uma outra. E legendar, essencial, precisamos fazer. Sei que é rápido, é reels, e justamente por isso precisamos promover que quem não consegue escutar possa ao menos ler. 

A Ascom respondeu sobre as artes?

**Comment by anapvcv** [comment]
> Certo, vamos lá. As imagens e áudios estão bem melhores... Embora ainda estejam caretas hehe, mas ok, considerando o contexto... Agora a gente precisa destacar algumas informações na tela, à medida que eles forem falando. Tipo, as especificidades e linguagens dos programadores que o Vitim cita (mobile, full stack - ver com ele como escreve isso), palavras-chaves na Camila, como Ciência de Dados e uma outra. E legendar, essencial, precisamos fazer. Sei que é rápido, é reels, e justamente por isso precisamos promover que quem não consegue escutar possa ao menos ler.
> 
> A Ascom respondeu sobre as artes?

Tá bem. E sim, vou legendar assim que Ascom enviar os templates, e o vídeo tiver no tamanho certo (vertical - 1080 x 1920). Mas eles ainda não responderam os e-mails.

**Comment by anapvcv** [comment]
Vídeo tutorial: https://drive.google.com/drive/u/0/folders/1or8yJVKCDHzu1SvWz301Ep8oCIuCBqPR

**Comment by anapvcv** [comment]
Vídeo tutorial - 2 corte: https://drive.google.com/drive/u/0/folders/1or8yJVKCDHzu1SvWz301Ep8oCIuCBqPR

**Comment by anapvcv** [comment]
vídeo tutorial - corte final - legendado: https://drive.google.com/drive/u/0/folders/1or8yJVKCDHzu1SvWz301Ep8oCIuCBqPR

**Comment by anapvcv** [comment]
reels - corte final, com opção legendada: https://drive.google.com/drive/u/0/folders/1Jqv_A3O8o-_lliSaajm0S6VkE6MDt8ah

**Comment by anapvcv** [comment]
> https://drive.google.com/drive/u/0/folders/1Jqv_A3O8o-_lliSaajm0S6VkE6MDt8ah

reels, versão legendada, foram aprovados pela Ariane! 

o vídeo tutorial ela pediu só pra abaixar o bg...

**Comment by Clarisse1983** [comment]
O teaser não foi produzido, mas as outras peças estão ok, no aguardo de divulgação pela Ascom.
