### ISSUE TITLE
Amigo criptografado

### ISSUE THREAD

**Issue by danielgula** [EscolaDeSaudePublica/FeliciLab#251]
## **Objetivo**

**Como** felicilaber
**Quero** participar do amigo secreto
**Para** comemorar o natal da equipe

## **Contexto**

A equipe do tático definiu que o amigo secreto se chamaria Amigo Criptografado, e seria uma brincadeira tradicional de troca de presentes. A demanda deve propor a dinâmica da forma mais efetiva possível.

## **Escopo**

- [x] Selecionar plataforma
- [x] Configurar grupo do amigo secreto
- [x] Criar texto de boas vindas
- [x] Criar release para o grupo
- [x] Moderar sorteio
- [x] Acompanhar realização

## **Critérios de Aceitação**

**Dado que** sou felicilaber  
**Quando** compareço ao evento
**então** participo do Amigo Criptografado

**Comment by danielgula** [comment]
https://www.amigosecreto.com.br/grupo/amigo-criptografado

**Comment by Clarisse1983** [comment]
@saracafe vai fazer uma chamada no telegram convidando a povo a se inscrever até amanhã final do dia, e o resultado será comunicado no Cuida, segunda.
