### ISSUE TITLE
Criar linha do tempo de entregas do Felicilab no site

### ISSUE THREAD

**Issue by Clarisse1983** [EscolaDeSaudePublica/FeliciLab#252]
## **Objetivo**

**Como** pessoa usuária da internet  
**Quero** visitar o site do Felicilab 
**Para** conhecer as entregas realizadas pelo NIT/Felicilab em 2021

## **Contexto**

- Estamos construindo um desenho das entregas feitas ao longo da existência do NIT/Felicilab para exposição aberta às pessoas. Criamos um relatório no doc, depois um desenho no Figma e agora vamos construir uma linha no tempo no site onde esse material fique disponível virtualmente de um jeito mais atrativo.

## **Escopo**

- [x] Validar as informações que serão disponibilizadas
- [x] Pesquisar soluções gratuitas que possam ser aplicadas no wordpress
- [x] Fazer o MVP da linha do tempo no site

## **Critérios de Aceitação**

- [x] visualizar linha do tempo no site do Felicilab 
**Dado que** estou no site do Felicilab  
**Quando** vejo a linha do tempo
**Então** conheço as entregas que foram realizadas na história do Felicilab

## Observações
Links de apoio e informações adicionais
https://www.figma.com/file/RUHP1EdXZ1GX70w71Nql71/Mapeamento-de-Entregas-NIT%2FFelicilab?node-id=0%3A1

**Comment by danielgula** [comment]
Esse é o card no sus.ce para a criação da página.

https://github.com/EscolaDeSaudePublica/sus.ce.gov.br/issues/129

**Comment by saracafe** [comment]
Textos para linha do tempo das entregas https://docs.google.com/document/d/1TucQDjeO6VYRujzX5e3fh3xh74mOhaaEepzb1BA550k/edit?usp=sharing
