### ISSUE TITLE
Criar artes para a 3ª ReuniãoZona

### ISSUE THREAD

**Issue by danielgula** [EscolaDeSaudePublica/FeliciLab#254]
## **Objetivo**

**Como** designer
**Quero** elaborar material visual do evento
**Para** utilização do time nas peças publicitárias

## **Contexto**

Precisamos montar as artes para a 3ª reuniãozona, que ocorrerá no dia 17/12/2021 com um clima natalino. É importante atualizar local e data.

## **Escopo**

- [x] Criar convite
- [x] Criar fundo de tela

## **Critérios de Aceitação**

**Dado que** sou felicilaber
**Quando** acesso algo da evento 3ª Reuniãozona
**então** vejo as artes aplicadas

**Comment by raiannyqz** [comment]
Vou elaborar uma arte para o evento, com base na foto enviada da galera.

**Comment by Clarisse1983** [comment]
@raiannyqz, sugestões para alterar a arte:
- Distribuir o texto de modo que fique sem o hifen separando trans-missão, e a transmissão é o Jitsi, link tá na agenda;
- Como tem muitas informações já no card, pode retirar esse quadrinho que tem a borboleta e estender a imagem;
- Retirar esse filtro azul da imagem;
- Alterar fontes, outra proposta mais suave.
