### ISSUE TITLE
Criar termos de uso de imagem

### ISSUE THREAD

**Issue by saracafe** [EscolaDeSaudePublica/FeliciLab#255]
## **Objetivo**

**Como** colaborador da DIT/FeliciLab  
**Quero** assinar termo de uso de imagem 
**Para** autorizar o uso de imagem em materiais da DIT/FeliciLab

## **Contexto**

O edital 26/2021 foi publicado e uma das estratégias de divulgação é utilizar fotografias das pessoas colaboradoras no ambiente de trabalho. Para isso, é preciso fazer um termo de uso de imagem para que as pessoas assinem e autorizem suas imagens serem divulgadas nos meios de comunicação, como redes sociais. 

## **Escopo**

- [x] Criar um termo de uso de imagem

## **Critérios de Aceitação**

- [ ] Autorizo o uso de imagem  
**Dado que** sou colaborador da DIT/FeliciLab  
**Quando** assino termo de uso de imagem   
**então** autorizo o uso da minha imagem em meios de comunicação

## Observações
Links de apoio e informações adicionais

**Comment by saracafe** [comment]
Termo: https://docs.google.com/document/d/1MMImH-POKf0frN92KCEpYQ4J5PnE7dhqkOU73E4hAME/edit?usp=sharing

**Comment by anapvcv** [comment]
Sara vai imprimir e solicitar as assinaturas.
