### ISSUE TITLE
Criar descrições para perfis do Edital 26

### ISSUE THREAD

**Issue by saracafe** [EscolaDeSaudePublica/FeliciLab#256]
## **Objetivo**

**Como** pessoa que tem interesse em se inscrever no Edital 26  
**Quero** saber a descrição dos perfis  
**Para** inscrever na vaga que se encaixar melhor

## **Contexto**

O Edital 26/2021 foi publicado e uma das estratégias de divulgação é criar uma pequena descrição para explicar as vagas, a fim da pessoa que se inscrever no Edital saber do que se trata e ver qual vaga se encaixa melhor no seu perfil. 

## **Escopo**

- [x] Criar descrição para vagas

## **Critérios de Aceitação**

- [x] Me inscrevo no Edital 26 
**Dado que** sou uma pessoa interessada em me inscrever no Edital 26 
**Quando** crio uma descrição para as vagas  
**então** me inscrevo no Edital na vaga que melhor se encaixa no perfil

## Observações
https://docs.google.com/document/d/1sgEowNgr8uoA0d1BGysQmDatuyutd2WqtKXfXy09ISU/edit?usp=sharing

**Comment by Clarisse1983** [comment]
Encaminhei o texto com os perfis para a Ascom. Agora é acompanhar e aprovar as artes, saber da publicação e respostar, bem como enviar nos grupos.
