### ISSUE TITLE
Divulgar edital 26 nos formularios de contatos mapeados

### ISSUE THREAD

**Issue by raiannyqz** [EscolaDeSaudePublica/FeliciLab#258]
## **Objetivo**

**Como** profissional inovador
**Quero** divulgar o Edital 26
**Para** que gere insterassados em se inscreverem no edital

## **Contexto**

- O Edital 26 possui 49 perfis profissionais, na qual foram mapeados contatos para divulgação do edital, agora precisamos fazer estes contatos. Para isso além dos contatos de email e telefone (que não está incluso nesta demanda) utilizaremos os próprios formulários que consta em seus sites para repassar o convite. 

## **Escopo**

- [x] Enviar o texto convite para os formulários que foram mapeados

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [x] titulo  
**Dado que** estou procurando oportunidades de trabalho
**Quando** recebo informações
**então** me inscrevo

## Observações
Links de apoio e informações adicionais

**Comment by raiannyqz** [comment]
Olá @Clarisse1983 nos formulários tem limite de caracteres, ou seja, aquele texto que você repassou está grande para enviar na íntegra.

**Comment by raiannyqz** [comment]
Nos formulários geralmente não falamos com humanos, o que complica a comunicação, como está apresentado na imagem  abaixo

<img width="248" alt="2222" src="https://user-images.githubusercontent.com/28989404/146971681-923ae6ab-2f7b-4b57-b869-ba1cecf0b54a.png">

**Comment by raiannyqz** [comment]
@Clarisse1983 os contatos por formulários foram realizados e os de whatsapp? Como serão feitos?

**Comment by raiannyqz** [comment]
@danielgula

**Comment by danielgula** [comment]
Oi Gente! Na pasta do drive referente a divulgação do edital 26, coloquei a planilha com todas as pessoas inovadoras que se inscreveram no edital 19. @Clarisse1983 com base em todos esses contatos levantados pela equipe, o encaminhamento é passar para que setor fazer os contatos (mailing, zap, etc)?

**Comment by raiannyqz** [comment]
> Oi Gente! Na pasta do drive referente a divulgação do edital 26, coloquei a planilha com todas as pessoas inovadoras que se inscreveram no edital 19. @Clarisse1983 com base em todos esses contatos levantados pela equipe, o encaminhamento é passar para que setor fazer os contatos (mailing, zap, etc)?

ótimo @danielgula encaminhei o email para a ASCOM! @Clarisse1983 e @saracafe e coloquei o link com o mapeamento também.
Essa tarefa pode ser fechada ou continua open?

**Comment by raiannyqz** [comment]
Tarefa Concluída!

**Comment by raiannyqz** [comment]
A última tarefa realizada foi: envie um email para ASCOM com o link do mapeamento de articuladores (https://docs.google.com/spreadsheets/d/1ROQSUPtxjhmvFJw4qox6QEFGZGOc6xM86SH-GO1M8pA/edit?usp=sharing) e de outro arquivo com emails dos inscritos no edital anterior, solicitando que eles possam inserir no mailing oficial, enviando as informações sobre o edital.
[2020-19-inscritos.ods](https://github.com/EscolaDeSaudePublica/FeliciLab/files/7771010/2020-19-inscritos.ods)
Os demais contatos serão feito individualmente pelo time publicilab através de contatos pessoais, grupos, amigos e etc.
Por isso este card será fechado!
