### ISSUE TITLE
Atualizar vídeo com depoimentos sobre o iSUS

### ISSUE THREAD

**Issue by Clarisse1983** [EscolaDeSaudePublica/FeliciLab#260]
## **Objetivo**

**Como** pessoa que atua com edição de vídeos no Felicilab  
**Quero** fazer algumas alteração em conteúdo já produzido (no link)
**Para** atualizar as informações antes de torná-las públicas

## **Contexto**

- O capítulo do livro será finalmente publicado em janeiro, e precisamos atualizar o conteúdo do mesmo, antes de torná-lo público.

## **Escopo**

- [x] Alterar abertura, substituindo a logo animada do Felicilab pela do sorriso, sem aquele pano de fundo colorido (veja o vídeo tutorial do Mapa como referência);
- [x] No depoimento do Victor, ver se é possível retirar as perguntas da fala dele, editando apenas com as respostas;
- [x] No depoimento do Luís, editar a legenda e a parte em que ele diz que é bolsista, e começar a partir de 1´38 (desde 2005...);
- [x] No vídeo da Gisele, tira o 'boa tarde' do começo.

## **Critérios de Aceitação**

- [x] Ver o vídeo na página de conteúdo extra do capítulo sobre o iSUS  
**Dado que** desejo acessar a página de conteúdo extra do iSUS, digital  
**Quando** visito a página  
**Então** assisto o vídeo atualizado

## Observações
O vídeo está aqui:
https://www.youtube.com/watch?v=L7zohpPQXyU

**Comment by danielgula** [comment]
@Clarisse1983 quando removo as duas primeiras perguntas que o Victor faz para ele mesmo a fala dele perde o sentido. Acredito que só consigo remover a última. Pode ver novamente?
Qual a legenda que eu coloco na parte do Luis?

**Comment by danielgula** [comment]
Segue arquivo do vídeo corrigido para aprovação:
https://drive.google.com/file/d/1eKXWcrALPFhmNn7V_Kyb0CN1O-ZQpSFj/view?usp=sharing

**Comment by Clarisse1983** [comment]
Pronto, aprovado! Substituir o anterior e ok.
