### ISSUE TITLE
Alterar e incluir perfis no site do Felicilab

### ISSUE THREAD

**Issue by Clarisse1983** [EscolaDeSaudePublica/FeliciLab#276]
## **Objetivo**

**Como** pessoa curiosa da inovação na internet 
**Quero** conhecer as pessoas do time do Felicilab
**Para** saber quem são os colaboradores do time

## **Contexto**

- Chegaram novas pessoas no time do Felicilab por meio do Edital 26, e precisamos inclui-los no site. Além disso, vamos reposicionar as pessoas que já foram colaboradoras e saíram, criando uma nova seção em "Quem somos" chamada "Já colaboraram conosco".

## **Escopo**

- [x] Adicionar novos perfis no site do Felicilab: Edmilson, Érica, Nazka, Lucas, Fernando, Jessé, Gabriela e Jorge
- [x] Posicionar perfis de ex-colaboradores em nova seção

## **Critérios de Aceitação**

- [x] Visualizar novos perfis no site do Felicilab 
**Dado que** sou uma pessoa curiosa da inovação na internet
**Quando** visito o site do Felicilab
**Então** vejo todos os colaboradores presentes, passados e futuros (brinks)

## Observações
Links de apoio e informações adicionais

**Comment by uira** [comment]
@Clarisse1983 @elpadrejorge @danielgula precisamos falar sobre sites

**Comment by danielgula** [comment]
Tarefa foi rapassada e atualizada na issue:
https://github.com/escoladesaudepublica/narrativas/issues/19
