### ISSUE TITLE
30.03 - Propor categorização para entrega personalizada de notificações do iSUS

### ISSUE THREAD

**Issue by ericabpinho** [EscolaDeSaudePublica/FeliciLab#277]
## **Objetivo**

**Como** Gestor da ESP
**Quero** Entregar informação relevante às pessoas usuárias do iSUS  
**Para** Qualificar o relacionamento com a força de trabalho do SUS

## **Contexto**

- Para reaproximar o iSUS dos profissionais e trabslahadores de saúde, estamos iniciando um fluxo de notificações personalizadas. A princípio, entregaremos notificações de conteúdos produzidos pela SESA e pela ESP. Para isso, é preciso criar uma categorização mínima para entrega de conteúdos, a partir das classificações já existentes no app.
- 

## **Escopo**

- [ ] Preparar uma planilha com as categorias já existentes no app. 
- [ ] Classificar cada uma das categorias como: profissional de saúde, gestor ou trabalhador da saúde. 

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [ ] titulo  
**Dado que** Sou gestor da ESP
**Quando** desejo entregar conteúdo personalizado à força de trabalho do SUS
**então** Posso disparar notificações personalizadas pelo iSUS

## Observações
Links de apoio e informações adicionais
https://docs.google.com/spreadsheets/d/1atlTmvqgPGOliTHTWzw09XzgARm4-quFicJ66KlLPG0/edit?usp=sharing
Planilha proposta.

Link para planilha criada https://docs.google.com/spreadsheets/d/1X4RlTN_v9GBXgz1UEnwDUIErUZUzXd8o6_nOduQA7ZU/edit?usp=sharing

**Comment by uira** [comment]
@ericabpinho 😍

**Comment by ericabpinho** [comment]
Foi proposta uma nova categorização e foi feito um figma dela: 
https://www.figma.com/file/m7Ubi6yhuRu4PUrvdmPVXD/Categorias-iSUS
