### ISSUE TITLE
Atuação editorial

### ISSUE THREAD

**Issue by Clarisse1983** [EscolaDeSaudePublica/FeliciLab#28]
Nosso trabalho de atuação editorial consiste em produzir, orientar, revisar e eventualmente corrigir textos que componham nossos projetos e produtos, contribuindo para que a linguagem seja clara, simples, e as narrativas sejam coerentes com nossos valores,  premissas e também diretrizes da saúde estadual e do SUS.

**Comment by uira** [comment]
@Clarisse1983 ❤️❤️❤️

**Comment by Clarisse1983** [comment]
Fechando no git por motivos de "não é uma issue".
