### ISSUE TITLE
[19/04] Divulgar a enquete Ih! Nova Live

### ISSUE THREAD

**Issue by edmirandajr** [EscolaDeSaudePublica/FeliciLab#280]
## **Objetivo**

**Como** pessoa interessada em inovação 
**Quero** responder ao formulário de enquete
**Para** indicar temas e horários

## **Contexto**

- Elaboramos uma enquete sobre os temas pré-selecionados de inovação, para as pessoas escolherem seus favoritos. E também poderem sugerir novos temas a serem abordados na live. 

## **Escopo**

- [x] criar formulário
- [x] definir canais de divulgação
- [ ] solicitar para ASCOM divulgação em mailing e telegram
- [x] recolher dados gerados
- [x] analisar dados
- [x] reavaliar temas, horários e agenda da live
- [ ] integrar form da enquete no instagram do Felicilab
- [ ] solicitar criação de link [sus.ce.gov.br/felicilab/ihnovalive](https://sus.ce.gov.br/felicilab/ihnovalive)

## **Critérios de Aceitação**

- [ ] titulo  
**Dado que** tive acesso à enquete
**Quando** tenho meus horários e interesses contemplados
**então** assisto e interajo com a live

## Observações
Links de apoio e informações adicionais

**Comment by uira** [comment]
@edmirandajr Importante vocês parearem pra @edmilsonmirandajr pegar os paranaues do WP + Divi...

**Comment by edmirandajr** [comment]
opa, eu deveria parear com quem @uira ? Com @danielgula ?

**Comment by Clarisse1983** [comment]
@danielgula, precisando de ti aqui para colocar essa enquete no site do Felicilab.
