### ISSUE TITLE
Inserir seção "informações importantes" no Onboarding no site

### ISSUE THREAD

**Issue by Clarisse1983** [EscolaDeSaudePublica/FeliciLab#287]
## **Objetivo**

**Como** pessoa colaboradora da inovação, especialmente os novos ingressos  
**Quero** acessar o conteúdo das informações importantes
**Para** conhecer os procedimentos e desenvolver minha autonomia

## **Contexto**

- Criamos uma seção com as principais informações para pessoas ingressas nos times da Ditec e ela não está aparecendo na seção de Onboarding do site do Felicilab. É importante inseri-la.

## **Escopo**

- [ ] Criar nova subseção na seção de Onboarding, intitulada "Informações Importantes". Conteúdo encontra-se aqui (item 12): 
https://docs.google.com/document/d/18yo0c3Rmk4m-OkJpgONjabZjDBgkFwGzWYNzp_AvqyY/edit#

## **Critérios de Aceitação**

- [ ] Visualizar as informações importantes 
**Dado que** sou uma pessoa ingressa no time de inovação  
**Quando** visito a seção de Onboarding no site do Felicilab  
**Então** visualizo as informações importantes 

## Observações
Links de apoio e informações adicionais

**Comment by Clarisse1983** [comment]
@danielgula, favor inserir essa tarefa na sua programação. Gracias.

**Comment by danielgula** [comment]
Página criada em:
https://sus.ce.gov.br/felicilab/onboarding/informacoes-importantes/
