### ISSUE TITLE
Bate-papo com BAs

### ISSUE THREAD

**Issue by Clarisse1983** [EscolaDeSaudePublica/FeliciLab#29]
Essa ação compõe o eixo 2 das nossas estratégias de comunicação digital e refere-se à iniciativa de relacionamento com os gestores dos projetos/produtos, com o intuito de acolher e propor estratégias de comunicação específicas para cada uma dessas soluções.

**Comment by uira** [comment]
@Clarisse1983 🚀🚀🚀❤️❤️

**Comment by Clarisse1983** [comment]
Fechando no git por motivos de "não é uma issue".
