### ISSUE TITLE
Escrever textos para o site do Felicilab

### ISSUE THREAD

**Issue by Clarisse1983** [EscolaDeSaudePublica/FeliciLab#3]
Aqui estão os textos que compõem a parte editorial do MVP do site do Felicilab.

https://docs.google.com/document/d/1IGCe-kQh5ZpBSmG_licV1UHkyv0HbsWnd0r_KkWnjno/edit#

Minibio: https://docs.google.com/document/d/1TOuIFa7Ds1cOlgOmvkFQIIt2Jgnl2m2abn1VJUil1F4/edit?usp=sharing

Fotos Time Felicilab: https://drive.google.com/drive/u/0/folders/1CrbHr085J1L0OmgKW-oxiedLa25M99W_

**Comment by Junior-Shyko** [comment]
Precisa de uma correção de uma palavra no Genilton.
![Captura de tela de 2021-01-25 20-04-44](https://user-images.githubusercontent.com/7341117/105777154-a5dde980-5f48-11eb-92f2-ef59a08e6c49.png)

**Comment by Clarisse1983** [comment]
@Junior-Shyko, a palavra está correta, é todes mesmo, com a vogal 'e' e não 'o'. Usamos assim para nos adequar e fortalecer a linguagem que reconhece a diversidade de gêneros para além do masculino e do feminino, reconhecendo que existem outras identidades e formas de ser e estar no mundo.

**Comment by Junior-Shyko** [comment]
Haaaaaaaa, agora eu entendi. Poxa, vou aprendendo tanto com vcs... mas que coisa boa.
