### ISSUE TITLE
Gerência fluxo de demandas com a Ascom

### ISSUE THREAD

**Issue by Clarisse1983** [EscolaDeSaudePublica/FeliciLab#30]
Em reunião realizada no dia 3 de fevereiro de 2021, na Ascom da ESP, definimos que nosso fluxo de trabalho seria organizado da seguinte maneira: reuniões mensais com eles para entendimento de demandas, e manutenção do fluxo de pedidos pelo email oficial do setor. Dúvidas pontuais, lembretes e demais urgências podem ser discutidas no grupo Estratégias Digitais, no telegram. 

Todos os emails enviados à Ascom são encaminhados com cópia para Clarisse, Uirá e Washington.

**Comment by danielgula** [comment]
Essa demanda permanente na verdade é um fluxo permanente, acordado entre as camadas de gestão, e por não gerar atividades específicas, deve ser tratada como tarefa de rotina e, portanto, decidimos fechá-la.
