### ISSUE TITLE
Cobertura pré-oficinas de Design de Serviços

### ISSUE THREAD

**Issue by ClarisCaval** [EscolaDeSaudePublica/FeliciLab#300]
Escrever o texto sobre as pré-oficinas e solicitar a publicação do mesmo no site da Escola pela Ascom, além de pauta na imprensa.

Escopo

Atualizar o texto no site, colocando mais fotos, vídeos
Mobilizar participantes da pré-oficina com a Ditec

**Comment by Clarisse1983** [comment]
Já atualizei a postagem no site, e a Ascom publicou hoje o texto no site da Escola. Erica já enviou convite no telegram individual de cada pessoa da Ditec, mobilizando para pré-oficina amanhã.
