### ISSUE TITLE
FeliciLive

### ISSUE THREAD

**Issue by Clarisse1983** [EscolaDeSaudePublica/FeliciLab#31]
FeliciLive é a live de inovação e tecnologias da ESP-CE. Pode se chamar assim ou outro nome, como Papo Inova Ação (por exemplo), para somar com a identidade do Papo Saúde, que já acontece às terças-feiras no instagram da Escola. O objetivo é ter um momento quinzenal para começarmos a posicionar estrategicamente na esfera pública as iniciativas que a Escola tem desenvolvido nesses campos, lembrando que os diálogos da inovação e das tecnologias com o campo da saúde também se constroem a partir dessas iniciativas. Assim como a própria disseminação do conhecimento e articulação com as comunidades de práticas, que são duas das principais atribuições do FeliciLab.

https://docs.google.com/document/d/1e7WA4A4QZ0Wnf6D6j7tgsHVxynSR2uwclXl569J467I/edit#heading=h.3v8p3p6rxicw

**Comment by danielgula** [comment]
Essa demanda está duplicada neste card:

https://github.com/EscolaDeSaudePublica/FeliciLab/issues/6

Portanto, será fechada.
