### ISSUE TITLE
Criar descrições para os grupos atualmente vigentes no Telegram e Whatsapp

### ISSUE THREAD

**Issue by Clarisse1983** [EscolaDeSaudePublica/FeliciLab#32]
Após o mapeamento dos grupos existentes, cuidar para que todos tenham descrições objetivas, claras e amigáveis sobre os objetivos dos grupos e das trocas de mensagens.

ESCOPO

- [x] levantar os grupos telegram
- [x] levantar os grupos whatsapp
- [x] validar grupos ativos
- [x] atualizar informações e documento
- [ ] executar as alterações na descrição dos grupos ativos

**Comment by uira** [comment]
@Clarisse1983 🌈🌈🌈🌈

**Comment by saracafe** [comment]
https://docs.google.com/document/d/1qYh2_uMDThoOibB063Jz25WQdi-0eVIzKXJzdY9z8bs/edit?usp=sharing

**Comment by danielgula** [comment]
@uira precisa colocar @Clarisse1983 como administradora de todos os grupos para inserir as descrições.
