### ISSUE TITLE
 Implementar/validar a exportação de todos os dados necessários pelo plugin de integração Mapas/SAGU

### ISSUE THREAD

**Issue by nestorufpe** [EscolaDeSaudePublica/FeliciLab#322]
## **Contexto**

Precisa ser definido e implementado os dados que serão consultados da API do MAPA pelo SAGU a fim de realizar o cadastramento de pessoas físicas no SAGU. 

## **Fora de Escopo**

- [ ] Considerar dados que serão exportandos da API do MAPA para o SAGU a fim de emitir declarações (ver épico #308)

## **Critérios de Aceitação**
- [x] Preparar plugin do MAPA para exportar dados do inscrito selecionado na oportunidade
**Dado que** o desenvolvedor
**Quando** clicar no botão "Passar dados para o SAGU" da tela de selecionados do MAPA
**então** visualizará dados dos inscritos selecionados no formado JSON 

- [x] Garantir que todos os dados do mapa necessários para a migração são expostos corretamente na api do mapa e aceitos no padrão de dados atual do SAGU
**Dado que** sou uma pessoa administradora da oportunidade do mapa
**Quando** clico no botão migrar selecionados
**então** será realizado o castrado automático de pf no SAGU

## Observações
Links de apoio e informações adicionais

**Comment by ricardopoppi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Integraes-de-Produtos-622f81f2eaf7c70010bd1495/issues/EscolaDeSaudePublica/FeliciLab/322?planning-poker) with ZenHub @victorMagalhaesPacheco @nestorufpe
