### ISSUE TITLE
Analisar consumo em disco das declarações

### ISSUE THREAD

**Issue by nestorufpe** [EscolaDeSaudePublica/FeliciLab#331]
## **Contexto**

- Levantar informações sobre a quantidade de certificados emitidos pela ESP nos últimos 3-5 anos com recorte: Cursos livres (en/pe/ex), Residências (médica e multi).
- Analisar consumo em disco e propor alternativas de armazenamento dos certificados se for o caso (conversa com analista de infra da ESP)

- [ ] Fazer o cálculo
- [ ] Contactar o Wandson da infraestrutura para saber o espaço disponível atualmente no servidor

## **Critérios de Aceitação**

- [ ] titulo_da_tarefa_de_aceitação_ou_que_deve_ser_entregue  
**Dado que** algo  
**Quando** faço  
**então** resulta

## Observações
 Foi estimado 1 sprint

**Comment by ricardopoppi** [comment]
Levantamentos realizados:
- Cada certificado vai consumir
- Atualmente o servidor onde está o Sagu e outros serviços tem 310Gb livres, com 33% em uso. Somente o serviço do Sagu consome em torno de 32Gb de espaço

Se cada certificado consumir 1,5MB (estimativa com base no tamanho do arquivo modelo), para emitir a média de 4.000 certificados por ano (estimado com a área e arredondado para cima) a vida útil do espaço do servidor é de 5 anos
