### ISSUE TITLE
Solucionar bug dos relatórios no mapa da saúde [planilha csv]

### ISSUE THREAD

**Issue by nestorufpe** [EscolaDeSaudePublica/FeliciLab#334]
## **Contexto**

- Quando o usuário realizar a ação de exportar planilha dos inscritos em uma oportunidade do Mapa da saúde está dando um problema em exportar no formato CSV quando na oportunidade tinha a informação do endereço do inscrito. 

## **Critérios de Aceitação**

- [x] Correção do bug de exportação de planilha 

## Observações
Links de apoio e informações adicionais

**Comment by vicmagpac** [comment]
@nestorufpe PR aceito pelo hacklab no core e atualizado no ambiente de homologação.
