### ISSUE TITLE
Documento norteador das nossas práticas (não mover daqui)

### ISSUE THREAD

**Issue by Clarisse1983** [EscolaDeSaudePublica/FeliciLab#34]
Este é o documento que criamos a muitas mãos, com todo o time envolvido, e que orienta e ancora nossos fazeres cotidianos. Divididas em eixos, as ações podem e vão refletir a construção de um processo de comunicação integrada - narrativas, comunicação interna e externa. Consultar, revisitar e questionar sempre que necessário.

https://docs.google.com/document/d/1kGGxV-2UvEif8AZ5pWaNfPP3Iofh-Qw0jrKjrsOQzuI/edit#

**Comment by danielgula** [comment]
Infelizmente precisamos mover isso daqui. Colocaremos o link desta issue como legado da tarefa 
https://github.com/EscolaDeSaudePublica/FeliciLab/issues/153
Card será fechado

**Comment by Clarisse1983** [comment]
Fechando no git por motivos de "não é uma issue".
