### ISSUE TITLE
Conhecer as plataformas alvos e entender como os dados estão armazenados

### ISSUE THREAD

**Issue by diegosilvachagas** [EscolaDeSaudePublica/FeliciLab#341]
## **Contexto**

- Entender como os dados então armazenados no analytics e metabase para pode entender o processo de padronização das informações no banco de dados DataLab.

## **Critérios de Aceitação**

- [x] Listar dados que serão armazenados (tipos e relacionamentos);
**Mapa da Saúde, iSUS, Cuidar Melhor, Elmo, FeliciLab, Manejo Clínico (Coronavírus)**
analytics-> https://docs.google.com/document/d/12Hh1BeY_2aMqCoQd3O195aoSsGqiNvTdwhaia8WpMDg/edit

**Mapa da Saúde,  iSUS, QualiQuiz, OTRs, Elmo**
metabase ->
Número de novos usuários que efetivaram o cadastro 
Número de oportunidades 
Número de inscritos nas oportunidades

- [x] Produzir indicadores do Mapa no metabase 
- [x] Sincronização com o Firebase (iSUS)
- [x] Acredito que os melhores intervalos sejam manter todo o período e o ultimo mês, principalmente devido aos relatórios mensais. Dessa forma, os dados do ultimo mês já seriam utilizados nos relatórios mensais dos produtos.

- [x] Outra coisa, onde tem "TODOS OS DADOS DO WEBSITE" podemos substituir por "Central de informações do SUS (Elmo, Felicilab e cuidar melhor)", pois fica mais fácil de entender essa informação.

- [x] Faço sugestão similar onde tem "SITE CORONA VIRUS" podemos substituir por "Site Coronavírus Ceará".

## Observações
Link dos bancos de dados dos produtos  (Analytics e metabase)
https://docs.google.com/spreadsheets/d/1YKhpyHMEBjAMDllL16W-a7NkZ4p9Ktaq6TzdnVQEatI/edit#gid=0

**Comment by nestorufpe** [comment]
A versão do Metabase (.41) que está sendo utilizada para a  execução da tarefa impossibilita a sincronização com Analytics do Google. Dessa forma, se faz necessário a atualização do Metabase para versão mais atual (.44)

print do erro -> https://drive.google.com/file/d/15thHy_uzstbb0akL27dDWqSv-8XnOWWi/view?usp=sharing

**Comment by JesseOliveiraUFC** [comment]
Uma vez que o Metabase foi atualizado, se faz necessário conhecer mais a fundo os detalhes dos indicadores a serem montados:

* Na visualização de novos usuários (e nas outas também) qual o intervalo de tempo a ser levado em consideração? Será o número de novos usuários por dia? por semana? mês?

* É interessante que seja visível somente o mês atual ou se faz necessário um filtro em que se escolhe o mês que se deseja ver?

* Temos 3 indicadores, inicialmente. Quando se falar em oportunidade, é somente as oportunidades criadas no Mapa da Saúde ou existem oportunidades em outros produtos?

* Na seção de inscritos por oportunidades, será necessário varias caixas para cada oportunidade ou será necessário um filtro para selecionar a oportunidade que se deseja analisar?

Por enquanto, são esses pequenos detalhes que precisam ser definidos.

**Comment by JesseOliveiraUFC** [comment]
Segue a visualização de alguns indicadores dos produtos. 

https://metabase.esp.ce.gov.br/public/dashboard/d4c5124b-ef89-4356-84c7-cccdc776dd99

Gostaria de um feedback sobre a visualização dos dados, se está bom, se precisa melhorar, etc.

* PS: Não consegui identificar a tabela do Analytics referente ao Mapa da Saúde. Ela existe ou vamos usar os dados do próprio Mapa pra isso?

**Comment by diegosilvachagas** [comment]
Oi Jessé, bom dia!

- O intervalo de tempo para manter na tela inicial pode ser o de um mês, mas seria interessante ter a possibilidade de selecionar um filtro com diferentes períodos (dias, meses ou anos).  

- Quando se falar em oportunidades são apenas as criadas no Mapa da Saúde.

- Seria interessante ter um filtro para selecionar a oportunidade que se deseja analisar.

- Segue o link da tabela do Analytics referente ao Mapa da Saúde: https://analytics.google.com/analytics/web/?authuser=1#/p257144259/reports/dashboard?params=_u..nav%3Dmaui%26_u.comparisonOption%3Ddisabled%26_u.date00%3D20210101%26_u.date01%3D20220731&r=lifecycle-acquisition-overview&ruid=lifecycle-acquisition-overview,life-cycle,acquisition&collectionId=life-cycle

Gostaria de alinhar algumas questões do Dashboard que foi criado. Podemos conversar hoje ;)

**Comment by diegosilvachagas** [comment]
link analytics isus: https://console.firebase.google.com/project/i-sus-b71e7/overview

**Comment by JesseOliveiraUFC** [comment]
Sobre os filtros de tempo em consultas no Analytics:

De acordo com o post https://github.com/metabase/metabase/issues/4766, filtros de datas para contultas NoSQL (Google Analytics, dentre outros) ainda não são suportados dentro do Metabase.

A definição do intervalo de tempo observado na dashboard é estática e deve ser implementada na montagem dos indicadores. Eu montei duas visualizações, contendo a visão temporal de todo o período e outra contendo somente os 3 últimos meses. 

As visualizações são do:
* número de acessos, 
* número de sessões e 
* número de páginas visualizadas.

Segue a dashboard para visualizações: https://metabase.esp.ce.gov.br/public/dashboard/d4c5124b-ef89-4356-84c7-cccdc776dd99

Gostaria de solicitar validação e feedback da dashboard para dar continuidade a essa atividade.

**Comment by diegosilvachagas** [comment]
- [x]  Acredito que os melhores intervalos sejam manter todo o período e o ultimo mês, principalmente devido aos relatórios mensais. Dessa forma, os dados do ultimo mês já seriam utilizados nos relatórios mensais dos produtos. 

- [x] Outra coisa, onde tem "TODOS OS DADOS DO WEBSITE" podemos substituir por "Central de informações do SUS (Elmo, Felicilab e cuidar melhor)", pois fica mais fácil de entender essa informação. 

- [x] Faço sugestão similar onde tem "SITE CORONA VIRUS" podemos substituir por "Site Coronavírus Ceará". 

- [x] Temos quer ver como adicionar os dados do iSUS e MAPA ao Dashboard. O do MAPA já temos os encaminhamentos, mas do iSUS temos que ver já que os dados tem essa relação com o firebase.

**Comment by diegosilvachagas** [comment]
Temos quer ver como adicionar os dados do iSUS e MAPA ao Dashboard. O do MAPA já temos os encaminhamentos, mas do iSUS temos que ver já que os dados tem essa relação com o firebase.

**Comment by JesseOliveiraUFC** [comment]
> * [x]   Acredito que os melhores intervalos sejam manter todo o período e o ultimo mês, principalmente devido aos relatórios mensais. Dessa forma, os dados do ultimo mês já seriam utilizados nos relatórios mensais dos produtos.
> * [x]  Outra coisa, onde tem "TODOS OS DADOS DO WEBSITE" podemos substituir por "Central de informações do SUS (Elmo, Felicilab e cuidar melhor)", pois fica mais fácil de entender essa informação.
> * [x]  Faço sugestão similar onde tem "SITE CORONA VIRUS" podemos substituir por "Site Coronavírus Ceará".
> * [x]  Temos quer ver como adicionar os dados do iSUS e MAPA ao Dashboard. O do MAPA já temos os encaminhamentos, mas do iSUS temos que ver já que os dados tem essa relação com o firebase.

Solicitações realizadas com sucesso.

**Comment by JesseOliveiraUFC** [comment]
Os dados do Mapa da Saúde estão armazenados em uma "property" do Google Analytics 4. Até o atual momento, o Metabase só trabalha com GA v3, sem nenhuma previsão de quando será desenvolvida essa nova funcionalidade.

Os dados da Central do SUS estão na versão 3 e em 2023 deverá ser obrigatoriamente migrados para a versão 4, se forem migrados, também perderão a conectividade com o Metabase.

Segue a resposta dos devs do Metabase:
![image](https://user-images.githubusercontent.com/97004339/186718538-a321c189-6468-4416-9847-977c4c353bbe.png)

Só nos resta avançar nessa atividade e deixar essa questão específica em backlog para verificação futura.

**Comment by JesseOliveiraUFC** [comment]
Segundo outra resposta obtida no fórum, a equipe do Metabase está trabalhando para implementar a conexão com GA4 e a feature estará disponível o mais rápido possível.

Segue a resposta:
![image](https://user-images.githubusercontent.com/97004339/186720744-5f9e79a7-c1d3-439a-bba1-7f318623ee74.png)

**Comment by JesseOliveiraUFC** [comment]
Foram inseridos dados referentes aos Projetos, Produtos, Oportunidades e Inscrições do Mapa da Saúde na Dashboard Integrada.
Após validação feita pelo Diego, foi solicitada a inserção de filtros temporais, pra limitar a busca por intervalos de datas.

- [x] Conexão com os Dados do Mapa da Saúde.
- [x] Criação da dashboard com os indicadores do Mapa da Saúde.
- [x] Inserção de filtro de data na Dashboard para os dados do Mapa.

Como os filtros ficam na parte superior da Dashboard, dá a entender que os mesmos funcionam para todos os dados e, por conta disso, foi solicitado que eles ficassem internos na dashboard junto aos dados do Mapa, mas essa é uma funcionalidade que o Metabase não possui e essa demanda não poderá ser atendida.

Segue documentação: https://www.metabase.com/docs/latest/dashboards/filters

Próxima etapa: Estudar e realizar a conexão do Metabase com os dados do iSUS, que estão armazenados no Firebase.

**Comment by JesseOliveiraUFC** [comment]
Conexão com os dados do iSUS realizada com sucesso. Nos encontramos na mesma situação, o Analytics do iSUS está na versão 4 e o Metabase ainda não possui compatibilidade com essa versão de propriedade. 

Foram implementados cards na Dashboard para visualizar dados de cadastros de usuários no iSUS que estão armazenados no banco de dados.

Creio que essa atividade esteja completa e que um novo card contendo os impedimentos deva ser criado e adicionado à coluna de backlog, para futura implementação.

**Comment by diegosilvachagas** [comment]
Hoje temos o Dashboard com as informações dos produtos do felicilab, como pode ser observada através do link: https://metabase.esp.ce.gov.br/public/dashboard/d4c5124b-ef89-4356-84c7-cccdc776dd99?projeto=

Apesar disso, diante da impossibilidade de implementação da conexão com GA4, os dados do analytics do MAPA e iSUS ainda não foram agregados ao Dashboard.  Portanto, será necessário aguardar a feature que logo estará disponível  para finalizar o Dashboard integrado dos produtos.
