### ISSUE TITLE
Integração do metabase com os indicadores da ESP Virtual e Moodle

### ISSUE THREAD

**Issue by nestorufpe** [EscolaDeSaudePublica/FeliciLab#346]
## **Contexto**

-Realizar gráficos com o monitoramento do perfil de quem acessa o site da ESP Virtual e Moodle nos anos 2020,2021 e 2022.

## **Critérios de Aceitação**

- [x] Visualização de indicadores da ESP Virtual 
- [x] Numero de acesso
- [x] Páginas mais acessadas
- [x] Cidades 
- [x] Dispositivo de acesso( celular, computador, tablet...)

## Observações
Links de apoio e informações adicionais

**Comment by JesseOliveiraUFC** [comment]
Integração realizada com sucesso. A atividade foi realizada junto com o Jackanderson na forma de consultoria.

Todos os indicadores foram visualizados com sucesso.

Atividade concluida com sucesso.
