### ISSUE TITLE
Tornar público os scripts de atualização dos profissionais e estabelecimentos de saúdes (CNES) no github

### ISSUE THREAD

**Issue by nestorufpe** [EscolaDeSaudePublica/FeliciLab#358]
## **Contexto**

- Os scripts hoje estão hospedados localmente e precisam se tornarem públicos.

## **Critérios de Aceitação**
- [x] Corrigir problemas no atual script
- [x] Fazer a dockerização
- [x] Comitar no Github

## Observações
Links de apoio e informações adicionais

**Comment by JesseOliveiraUFC** [comment]
Scripts de atualização dos dados de estabelecimentos e profissionais publicizados com sucesso.
O repositório onde os arquivos foram upados pode ser encontrado no link: https://github.com/EscolaDeSaudePublica/estab_prof_actualization.

Uma breve descrição do processo e uma imagem com o fluxograma de atualização foram inseridos no repositório.
