### ISSUE TITLE
[18/03/2021] Análise das descrições dos repositórios GitHub

### ISSUE THREAD

**Issue by Clarisse1983** [EscolaDeSaudePublica/FeliciLab#37]
As descrições dos nossos repositórios e projetos são muito aleatórias. Não têm um roteiro de informações essenciais, são muito distintas em tamanho e qualidade. Dar uma melhorada nisso.

Usar a descrição do ID Saúde como referência:
https://github.com/EscolaDeSaudePublica/IdentidadeUnicaDeSaude/wiki

[ ] Criar um template padrão para descrições dos repos. Sugestão: Texto descritivo + Quem faz + Links dos projetos (como o exemplo do ID Saúde)
[ ] Analisar os textos dos boards, corrigindo ou organizando a informação
[ ] Publicar no read.me após validação com BAs

**Comment by saracafe** [comment]
https://docs.google.com/document/d/1EStERPZwRpLOpZEYjgbXy3gud6QChAWXD60--_coV3A/edit?usp=sharing

**Comment by saracafe** [comment]
Planilha para melhor visualização: https://docs.google.com/spreadsheets/d/1L7RTBLudJDKbTTRMZmmhtKV2unWUM4KwmLPlznnbKOw/edit?usp=sharing

**Comment by Clarisse1983** [comment]
@saracafe, precisamos acrescentar uma coluna nessa análise, por  sugestão da Camila: tipo de repositório - classificando em três tipos: Gestão, Software e Gestão de Software. Te explico a diferença quando retomarmos essa tarefa.
