### ISSUE TITLE
NIT em Transformação

### ISSUE THREAD

**Issue by Clarisse1983** [EscolaDeSaudePublica/FeliciLab#38]
## **Objetivo**

**Como** pessoa colaboradora do NIT/FeliciLab  
**Quero** saber do evento NIT em Transformação  
**Para** participar ciente das informações principais

## **Contexto**

- O Núcleo de Inovação Tecnológica da ESP foi oficializado com a publicação da Política de Inovação da Escola de Saúde Pública no Diário Oficial do Estado do Ceará, em 25 de junho. Agora nós existimos de direito, e não apenas de fato. Nossos times seguem crescendo e despertando a curiosidade de toda a Escola. Quem somos? O que fazemos? Onde estamos distribuídos? Cada um dos componentes desse time tem alcance sobre esse processo? Entende a dimensão do que está acontecendo? Como Núcleo recém nascido, se torna fundamental alinhar as narrativas, dirimir as dúvidas e seguir acolhendo e nos alimentando da potência das diversidades. O evento NIT em Transformação teve um primeiro momento, com a chegada de Alice ao time, e terá agora um segundo encontro, presencial, para que possamos nos conhecer, reconhecer, e alinhar as expectativas sobre o presente, ainda pandêmico, e o futuro, com projetos e entregas que precisam acontecer.

- Texto para convite:
Convocação real oficial: reserve sua agenda para a próxima quinta-feira, 8 de julho! Teremos um dia inteiro de encontro presencial para nos revermos, ou nos vermos pela primeira vez, e alinharmos nossos olhares, expectativas e percursos. É o encontro do NIT em Transformação em sua segunda versão, onde vamos atualizar nosso contexto, apresentar os novos modelos de gestão, dialogar sobre as modalidades de trabalho presencial e remota, entre outras questões. Tragam disposição, papel, caneta e ideias, que a chapa vai esquentar, e vai ser muito bom. Ah, e essa é a prioridade para todes nesse dia, certo? Queremos ver 40 rostinhos juntos pela primeira vez na história dessa comunidade! Vai ser no auditório central, com início às 9h! ❤️

## **PubliciLab**

- [x] Fechar programação junto ao tático hoje, 05.07
- [x] Criar vídeo de abertura, ver com Ana Paula
- [x] Criar agenda convidando todos os participantes, com link para quem não poderá estar presencial
- [x] Estruturar linha do tempo que será apresentada por dinâmica ou por fala do Uirá
- [x] Solicitar cobertura da Ascom

## **DesignLab**

- [x] Fazer arte para o evento
- [x] Arte para Powerpoint
- [x] Arte para convite
- [x] Motion de abertura para vídeo pós-evento

## **Critérios de Aceitação**

- [x] Divulgar e mobilizar para evento NIT em Transformação, dia 08.07  
**Dado que** sou um um colaborador do NIT/FeliciLab 
**Quando** vejo a programação
**Então** me aproprio do evento e das informações essenciais

## Observações
Links de apoio e informações adicionais

https://docs.google.com/document/d/1Wa2wSs_FZMJ5TKkDrnT_pP_5R5RtfAVLUdbxxmb2gIA/edit#

**Comment by saracafe** [comment]
@uira dá uma olhada nessa proposta do Chega Mais: https://docs.google.com/document/d/1Wa2wSs_FZMJ5TKkDrnT_pP_5R5RtfAVLUdbxxmb2gIA/edit?usp=sharing

**Comment by uira** [comment]
@saracafe Achei ótimo. 

Queria entender melhor a proposta de cada um dos momentos propostos ali na programação, e fazer algumas sugestões

**Comment by Clarisse1983** [comment]
@uira, dá uma olhada agora que eu escrevi as descrições dos momentos propostos.

**Comment by Clarisse1983** [comment]
Proposta encaminhada ao Grupo tático, para validação de formato e definição de data.

**Comment by Clarisse1983** [comment]
O evento 'NIT em [Trans]formação', realizado em 27.04.21, cumpriu bem os objetivos desse evento, de aproximação e integração do NIT/FeliciLab com Super, com Alice e entre nós. Portanto vou fechar essa issue.

**Comment by uira** [comment]
@Clarisse1983 Opa! Revisei o roteiro e não acho que o que rolou substitiui esse momento que estava sendo planejado.

Porque precisamos fazer isso, e não só voltado para SUPER e Adins, mas para toda ESP e a sociedade. 

Então sugiro reabertura da issue, revisão do formato (em poucas coisas, pq no geral tá enxuto e direto)

Talvez tirar o momento de "debate", que não rola mesmo, ainda mais online, e incluir uma apresentação dos times e seus respectivos projetos e produtos. 

E o último ponto, do manifesto da colaboração, é massa e super importante. 

Que acham de programarmos esse evento para o final de maio ~ começo de junho, pra ficar perto ou até junto do lançamento do NIT?

E aproveitar a provocação do Marcelo pra fazer um hackathon ou pelo menos algumas oficinas, ligadas às nossas práticas, projetos e produtos.

**Comment by Clarisse1983** [comment]
Beleza @uira, vamos conversar sobre isso então, e botar pra frente.
