### ISSUE TITLE
[22/03/21] Vídeo comemorativo de 1 ano do FeliciLab

### ISSUE THREAD

**Issue by saracafe** [EscolaDeSaudePublica/FeliciLab#41]
- Roteiro: https://docs.google.com/document/d/13ThM32-vDLcR3-CT8ev-1C2Ylajlu-BpTOuL6aJPa60/edit
- Imagens: https://photos.google.com/share/AF1QipMts5WtLt1EvhNu_CeJTvk87Yp7u5qSKffzpVYQ_-BOVdKk_Vm0MzIT5ln92FPccQ?key=Ti1uZG9rSV8zTDFNRklNalJOZHA0cE1LU3lORFZB
- Sonoras: https://drive.google.com/drive/u/0/folders/10m_2buLi5RH_Y9DMPaS9B9a6Y5-dRQ1e
- Edição de vídeo: @danielgula

**Comment by Clarisse1983** [comment]
@danielgula, alguns pequenos ajustes na versão atual, especialmente em legendas:
1) Na legenda 'É Trello e cards...', retirar esse 'É' do início;
2) Substituir a foto da Olivia, que tá péssima, vou achar outra e colocar no roteiro;
3) Na legenda da foto da cúpula com o Elmo, inserir a correta 'Elmo e seus muitos pais';
4) Retirar a legenda 'Manhê, estou na TV' e colocar 'Cerca de 2000 Elmos doados ao SUS no Ceará'.

Uirá vai assistir e deve dar mais algum palpite, ou alguns, rs.

**Comment by Clarisse1983** [comment]
@danielgula, inseri as sugestões do Uirá no roteiro. São inserções de novas imagens, e uma alteração de audio no início, que Helen já gravou e já coloquei na pasta, certo?
