### ISSUE TITLE
Elaboração dos perfis dos novos componentes do FeliciLab

### ISSUE THREAD

**Issue by Clarisse1983** [EscolaDeSaudePublica/FeliciLab#44]
Novos colaboradores chegaram no FeliciLab, e precisamos elaborar seus perfis para o site.

- [x] Avaliar se todos responderam o form no google
https://docs.google.com/forms/d/1rYy2ABZNvPruIICa09tYHy0-ltRm89kpFA67upXM00c/edit

- [x] Elaborar os textos que faltam no documento
https://docs.google.com/document/d/1TOuIFa7Ds1cOlgOmvkFQIIt2Jgnl2m2abn1VJUil1F4/edit

**Comment by RaniGub** [comment]
Acordado em Daily que todos os esforços para conclusão da tarefa foram executados. Faltando apenas o preenchimento do formulário por duas pessoas. Esta tarefa é de ordem contínua, sendo que uma nova será aberta na chegada de um novo(a) Felicilaber.
