### ISSUE TITLE
Cards O que é FeliciLab

### ISSUE THREAD

**Issue by Clarisse1983** [EscolaDeSaudePublica/FeliciLab#48]
A Ascom está criando materiais explicativos sobre todos os setores da ESP e suas funções. Em nossa reunião, eles falaram sobre fazer isso para o FeliciLab, até aproveitando a efeméride de 1 ano do lab. Então, precisamos responder essas 5 perguntinhas, e encaminhar pra eles:

O que o Felicilab faz?
Quais seus objetivos?
Quais os integrantes da equipe?
Quais as principais atividades executadas pelo Felicilab?
Caso as pessoas queiram solicitar algum serviço aos felicilabers, como ela pode fazer?

Documento de referência:
https://docs.google.com/document/d/1V_qCI5E1FP5dgfYN9ER5uzT-ZMxBsH33obGWZhYwsvs/edit?usp=sharing

**Comment by saracafe** [comment]
Material explicativo sobre o Felicilab
https://docs.google.com/document/d/1VTJmJpdRLCYqjJFHvW9r3p8faDIrlvmwhgFZueLq3c4/edit?usp=sharing
