### ISSUE TITLE
[19/05] Produzir versão 2 do Fala, meu povo

### ISSUE THREAD

**Issue by Clarisse1983** [EscolaDeSaudePublica/FeliciLab#49]
## **Objetivo**

**Como** felicilaber ou outra pessoa interessada em conhecer os processos internos do lab 
**Quero** acessar o Fala, meu povo 
**Para** receber atualização sobre temas relevantes na gestão de inovação

## **Contexto**

- O 'Fala, meu povo' é um espaço informativo da ambiência de gestão do FeliciLab direcionado aos seus colaboradores. Tivemos até hoje uma única postagem no blog com informes importantes, mas a ideia é seguir com esses conteúdos, assinados por diferentes pessoas do grupo tático. Sugestão de pauta para a próxima edição: o desafio de fazer uma seleção diversa e ao mesmo tempo eficiente para o campo da TI, usando o processo de elaboração de nosso TAP como case. 

## **PubliciLab**

- [x] Conversar com Uirá sobre essa ideia
- [x] Definir formato e tratamento do material

## **DesignLab**
- [x] Criar uma identidade para esse espaço informativo. Assim como o Cuida! tem sua logo (ou sua arte), esse produto também precisa ter a sua. Inclusive pode se chamar outra coisa
- [x] Criar as artes: para blog (imagem grande mais horizontalizada e thumbnail de destaque), instagram e canal no telegram (pode ser a mesma do instagram)
- [x] Criar miniatura para o Youtube

## **Critérios de Aceitação**

- [x] Disseminar conteúdos sobre gestão na inovação
**Dado que** sou usuária de plataformas digitais do FeliciLab
**Quando** visito seus canais
**então** consigo acessar o Fala, meu povo

## Observações
Links de apoio e informações adicionais

**Comment by Clarisse1983** [comment]
Conversei com @uira sobre essa sugestão e tema e formato e ele prefere que seja um texto e que seja sobre outro tema, que é a estruturação do NIT a partir da chegada da Alice. Vai me enviar um audio, para que eu construa a proposta.

**Comment by danielgula** [comment]
![image](https://user-images.githubusercontent.com/39468037/118129146-3219fc80-b3d2-11eb-82a4-fa29c23fa554.png)

Primeira versão para aprovação. @saracafe @Clarisse1983

**Comment by Clarisse1983** [comment]
Huuum, não curti, @danielgula. Muito simples. Vamos tentar uma coisa mais convidativa?

**Comment by pauloamoreira** [comment]
olá. segue nova proposta de imagem para o "Fala, Meu Povo"
![FalaMeuPovo](https://user-images.githubusercontent.com/79201419/118541489-2018c080-b728-11eb-910c-5f856f974b10.png)

**Comment by uira** [comment]
@pauloamoreira Quiser colocar um fundo psicodélico fica melhor ainda... 😘🌈

**Comment by pauloamoreira** [comment]
@uira vai depender da aplicação né? mas já vou fazer uns testes aqui :)

**Comment by Clarisse1983** [comment]
Achei mara, @pauloamoreira! Pra mim já tá super psicodélico kkkk

**Comment by pauloamoreira** [comment]
.sobre a demanda: "_Conseguimos pensar num padrão de enquadramento para esses vídeos curtos? Com alguma espécie de filtro, ou legenda? É uma pergunta mesmo tá, e gostaria de uma proposta_". acredito que estejam falando de criar uma LOWER THIRD (uma barra que aparece no vídeo com a marca e o nome do personagem no vídeo, geralmente fica no rodapé. é bem comum nos programas jornalísticos. é isso?

**Comment by Clarisse1983** [comment]
Sim, bem isso Paulo. Mas também pensei em outros elementos possíveis de
serem usados e que se relacionem com o FeliciLab, como filtros, cores e
outros elementos de edição. Mas acho que devemos refinar isso depois, uma
vez que por hora não vai mais ser vídeo, e sim texto.

*Clarisse Castro Cavalcante*
Jornalista pela Universidade Federal do Piauí.
Especialista em Teorias da Comunicação e da Imagem pela Universidade
Federal do Ceará.
Mestre e Doutora em Informação e Comunicação em Saúde pela Fundação Oswaldo
Cruz (RJ).
85.981116986





<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Em seg., 17 de mai. de 2021 às 16:53, Paulo Amoreira <
***@***.***> escreveu:

**Comment by pauloamoreira** [comment]
.segue duas opções para miniatura para youtube (se formato):
![FalaMeuPovo_youtube-2](https://user-images.githubusercontent.com/79201419/118665646-d7651400-b7c8-11eb-80ab-d6d9bed62e9c.png)
![FalaMeuPovo_youtube-1](https://user-images.githubusercontent.com/79201419/118665664-daf89b00-b7c8-11eb-8ec5-5990e365ccfc.png)

**Comment by Clarisse1983** [comment]
@pauloamoreira, considerando o que conversamos hoje na daily, editei o escopo para o DesignLab especificando as artes que precisamos para esse conteúdo editorial. As ideias estão maravilhosas, é só adaptar o formato.

**Comment by pauloamoreira** [comment]
. @Clarisse1983 analisem essas três opções de background para o ícone do FalaMeuPovo. para que vocês indiquem qual caminho devo seguir para fazer as outras aplicações:
![horizontal_blog-3](https://user-images.githubusercontent.com/79201419/119710401-b0e05200-be34-11eb-8f2a-8bcbbe532832.png)
![horizontal_blog-1](https://user-images.githubusercontent.com/79201419/119710415-b63d9c80-be34-11eb-9152-4e6fcc0464e6.png)
![horizontal_blog-2](https://user-images.githubusercontent.com/79201419/119710428-b9d12380-be34-11eb-88ab-d3903d712a8a.png)

**Comment by Clarisse1983** [comment]
@pauloamoreira e se eu disser que amei todos? Ow meu pai... Não podemos ficar com todos, não? Um pra cada edição?

**Comment by pauloamoreira** [comment]
@Clarisse1983 podemos sim. qual a periodicidade? assim faço um pack de materiais para um determinado período.

**Comment by Clarisse1983** [comment]
Mensal @pauloamoreira =)

**Comment by pauloamoreira** [comment]
@Clarisse1983 criei uma pasta no drive do PubliciLab com artes para 4 meses, usando os padrões já aprovados.
