### ISSUE TITLE
Liberou geral!

### ISSUE THREAD

**Issue by Clarisse1983** [EscolaDeSaudePublica/FeliciLab#50]
Alô, meu povo! Integrando o movimento celular cósmico que produz nossa sinergia por fibra ótima, separamos essa horinha de todas as nossas sextas-feiras para realizar nosso momento integração FeliciLab. É legal poder trabalhar remoto, síncrono e assíncrono, mas brincar junto também é bom, né? Rir, descontrair, falar bobagem, descobrir talentos, alongar, rezar, conversar sobre coisas off desenvolvimento... Pois bem! Então manda um 'sim' aí nessa agenda e vamos juntes!

Como participar? Entra nesse link do discord, no canal de voz do FeliciLab. E também no link da atividade do dia, que varia.

https://docs.google.com/document/d/161WlCZFzb_wzltMNtVaitYsJK7NNykwb3ptUGTs4pDM/edit

**Comment by danielgula** [comment]
Essa iniciativa precisa de planejamento, PO, BA, GP, e todas as siglas possíveis para se melhor estruturado, isto é, um planejamento melhor.

**Comment by Clarisse1983** [comment]
Fechando no git por motivos de "não é uma issue".

**Comment by Clarisse1983** [comment]
Fechando no git por motivos de "não é uma issue".
