### ISSUE TITLE
Marcar teste de evento de integração com Genilton + duas pessoas

### ISSUE THREAD

**Issue by saracafe** [EscolaDeSaudePublica/FeliciLab#52]
Primeiro será feito um teste da atividade, que ocorrerá na próxima semana. Depois encaixaremos a atividade no calendário de integração para todo o grupo.

Preparativos: copo de água perto para beber, papel, caneta e lápis de cor (se tiver, melhor ainda) e uma música que relembre a infância. Será no Meet.

**Comment by Clarisse1983** [comment]
@saracafe, falta só mobilizar as pessoas e ajustar a data. Sugiro Genilton, Junim, Helen e eu. Vê se todes topam e conseguem na terça, 20/04, às 16h.

**Comment by saracafe** [comment]
Falei com Helen e super topou de participar, se caso não aparecer alguma urgência antes. Junin disse que fica com pouco de vergonha por ser a primeira vez que a atividade vai rolar, mas que talvez se solte nos próximos quando for acontecendo
