### ISSUE TITLE
Criar evento sobre SEO para público interno (FeliciLab/ESP)

### ISSUE THREAD

**Issue by Clarisse1983** [EscolaDeSaudePublica/FeliciLab#53]
Marcos Oliveira fez a proposição de fazer uma oficina sobre SEO com os integrantes do FeliciLab. Só temos o título: "Como e porque trabalhar questões de SEO (Search Engine Optimization) em nossas atividade com sistemas web. Um bate papo para sairmos na frente nos mecanismos de buscas". Acho ótimo para o card. Agora precisamos:

[X] Fazer um texto pequeno de apresentação do assunto, para acompanhar o card de divulgação. Peguei esse material na internet, pode ajudar:
https://docs.google.com/document/d/1c3wo47dRlUTpifP4VjajWtm8YzkeY4jueW-wfEQXTrQ/edit
[X] Com o texto, solicitar aprovação do Marcos e sugestão de data para execução da oficina
[X] Fazer o briefing para Ascom, solicitando card e apoio na divulgação (vamos abrir para a Escola, para quem quiser)
[X] Inserir em nossa agenda e programar a divulgação interna

**Comment by saracafe** [comment]
@drmarcos Dá uma olhada no texto de apresentação da Oficina de SEO para mandar para Ascom, se tiver alguma outra sugestão pode colocar: https://docs.google.com/document/d/1c3wo47dRlUTpifP4VjajWtm8YzkeY4jueW-wfEQXTrQ/edit?usp=sharing

E também precisamos de uma data e horário para essa atividade.

**Comment by saracafe** [comment]
Definimos a data do evento que será na quarta-feira, 28/04, às 10h pelo Meet (já criei a sala) e aqui o briefing que vai ser enviado a Ascom para eles criarem o card e apoiarem na divulgação interna https://docs.google.com/document/d/1c3wo47dRlUTpifP4VjajWtm8YzkeY4jueW-wfEQXTrQ/edit?usp=sharing

**Comment by saracafe** [comment]
![esp-ce - Evento online sobre SEO (Search Engine Optimization)versão youtube](https://user-images.githubusercontent.com/77791759/114924776-b80f4b80-9e04-11eb-947b-58bb917402cd.jpg)
![esp-ce - Evento online sobre SEO (Search Engine Optimization)versão redes sociais](https://user-images.githubusercontent.com/77791759/114924784-b9407880-9e04-11eb-8e30-de3315e68430.jpg)
![esp-ce - Evento online sobre SEO (Search Engine Optimization)versão site](https://user-images.githubusercontent.com/77791759/114924790-bba2d280-9e04-11eb-9a02-e43053b860b6.jpg)
