### ISSUE TITLE
Produzir Ih! Nova Live

### ISSUE THREAD

**Issue by Clarisse1983** [EscolaDeSaudePublica/FeliciLab#6]
## **Objetivo**

**Como** ser humano interessado em assuntos inovadores 
**Quero** acompanhar as lives do FeliciLab 
**Para** conhecer os debates propostos

## **Contexto**

- Ih! Nova Live é uma live de inovação e tecnologias da ESP-CE. O objetivo é ter um momento quinzenal para começarmos a posicionar estrategicamente na esfera pública as iniciativas que a Escola tem desenvolvido nesses campos, lembrando que os diálogos da inovação e das tecnologias com o campo da saúde também se constroem a partir dessas iniciativas. Assim como a própria disseminação do conhecimento e articulação com as comunidades de práticas, que são duas das principais atribuições do FeliciLab.

## **Escopo**

- [x] Definir Linha Editorial 
- [x] Definir com Ascom um canal onde faremos essas lives
- [x] Definir com Ascom sobre estratégia de divulgação dessas lives
- [x] Mapear possíveis participantes
- [x] Definir o fluxo de produção, com respectivos representantes

## **Critérios de Aceitação**

- [x] Executar live de inovação  
**Dado que** sou pessoa interessada em inovação
**Quando** tomo conhecimento da live
**Então** posso acompanhá-la e interagir com o tema e as pessoas

## Observações
https://docs.google.com/document/d/1e7WA4A4QZ0Wnf6D6j7tgsHVxynSR2uwclXl569J467I/edit#
https://docs.google.com/document/d/1zsRnC-sh9tBask6H8Av7ohk82LZ-WC7koWQRb3OKioc/edit
https://docs.google.com/document/d/1NT8tC2V3rQRQA_zqKaDkx3o_cAoaLT466dnDOECvTUM/edit#heading=h.uk04eu9yn65r

**Comment by saracafe** [comment]
@uira estamos refinando a FeliciLive. Fizemos um roteiro para a primeira live com o Danilo Doneda, ta aqui nesse link: https://docs.google.com/document/d/1e7WA4A4QZ0Wnf6D6j7tgsHVxynSR2uwclXl569J467I/edit#heading=h.cypbtz8do9ja

Pode dar uma olhada, para ver como tá e se é isso mesmo

**Comment by saracafe** [comment]
@uira Nesse outro doc temos algumas sugestões de convidados: https://docs.google.com/document/d/1uZcpsPoH0uPNIJ8cSlfAQHky3fxUWhjwC2XqxfAe2ro/edit?usp=sharing

Pode colocar mais sugestões e contatos

**Comment by uira** [comment]
Vi aqui os dois documentos, mas senti falta de uma coisa: uma definição
mais clara do "Produto" felicilive.

Qual o formato? Tempo?
Qual o objetivo? E público?

E fiquei pensando que estrear com esse tema que é uma Sigla complexa, pode
não ser uma boa... talvez possa começar falando e contando a história do
próprio FeliciLab,  que acham?

>

**Comment by Clarisse1983** [comment]
@uira dá uma olhada de novo no documento, que eu atualizei essas questões.

**Comment by Clarisse1983** [comment]
Encaminhei hoje email para Ascom com nossa proposta de live. O documento está aberto para críticas e sugestões.

**Comment by Clarisse1983** [comment]
Enviei outro email para a Ascom hoje, que em fevereiro tinha ficado de dar uma olhada nisso.

**Comment by Clarisse1983** [comment]
Acordamos (de boca) com a Ascom que as lives iniciariam em janeiro, e precisamos atualizar os convidados. @uira

**Comment by edmirandajr** [comment]
@Clarisse1983 @uira tem aqui o documento com o roteiro para o primeiro episódio, dia 24 de março, quinta-feira https://docs.google.com/document/d/1zsRnC-sh9tBask6H8Av7ohk82LZ-WC7koWQRb3OKioc/edit?usp=sharing

**Comment by Clarisse1983** [comment]
A Ih! Nova Live estreou com sucesso ontem no canal da ESP, e agora vamos rodar uma enquete nos canais da Escola para priorizar temas que pensamos para os próximos roteiros. Parabéns pra nós, mais uma (re)existência!
