### ISSUE TITLE
Calendário de publicações

### ISSUE THREAD

**Issue by saracafe** [EscolaDeSaudePublica/FeliciLab#60]
Planilha de conteúdos: https://docs.google.com/spreadsheets/d/1bQV9DHiZ_XEpk8AnpcFR_r9jqdWFpTKgQtiK9k-A3II/edit?usp=sharing

**Comment by danielgula** [comment]
Essa atividade permanente deverá ser pensada em conjunto com ASCOM no GT.

**Comment by Clarisse1983** [comment]
Fechando no git por motivos de "não é uma issue".
