### ISSUE TITLE
[23/04/21] Criar post para o Dia da Propriedade Intelectual

### ISSUE THREAD

**Issue by Clarisse1983** [EscolaDeSaudePublica/FeliciLab#61]
O Dia da Propriedade Intelectual é comemorado em 26 de abril. Como é uma data que se relaciona com o que fazemos, vamos fazer um post sobre o tema para o instagram, e precisamos da arte para acompanhar o post. Sara vai escrever o conteúdo.

Escopo
[ ] Sara vai escrever o conteúdo. Recomendo conversar com Rodrigo Silvestre sobre como a questão da propriedade intelectual está relacionada ao FeliciLab.
[ ] DesignLab vai criar o card com base no texto que Sara vai escrever
[ ] PubliciLab aprovar e publicar dia 26

**Comment by saracafe** [comment]
Texto: https://docs.google.com/document/d/1l8be8XdQZ7EGU2Gv3JOkCdILYQ3x0bMHxUgB2ADRACw/edit?usp=sharing
