### ISSUE TITLE
[05/05] Criar arte para o Dia da Comunidade

### ISSUE THREAD

**Issue by saracafe** [EscolaDeSaudePublica/FeliciLab#63]
Dia 5 de maio é o Dia da Comunidade, e é uma data importante para fazermos um post nas redes sociais. O conteúdo estará relacionado à importância de trabalhar em comunidade, de forma colaborativa, e em contato com o ecossistema de práticas. Precisamos de card, ou cards, para instagram com esse tema.

**Escopo**
 [ ] Sara vai escrever o texto da postagem
 [ ] DesignLab vai criar o conteúdo gráfico até 03/05
 [ ] Vamos publicar em 05/05

**Comment by saracafe** [comment]
Texto para revisar https://docs.google.com/document/d/123D__kHBV1xdi3jcWqow1DKVnJn8I60316KjmYapwoA/edit?usp=sharing

**Comment by pauloamoreira** [comment]
Layout do Card para aprovação: [https://drive.google.com/drive/folders/1SaVZfBdWhxTZKif635npSyxxGPdp_qJ6?usp=sharing]

**Comment by wforte88** [comment]
@pauloamoreira @ClarisCaval card tá lá aguardando aprovação

**Comment by Clarisse1983** [comment]
Achei lindo, @pauloamoreira! Ornou com a narrativa, rs.
