### ISSUE TITLE
Apresentação FeliciLab para secretário de saúde

### ISSUE THREAD

**Issue by Clarisse1983** [EscolaDeSaudePublica/FeliciLab#7]
Temos um projeto do FeliciLab no trello, de estruturação do laboratório, que foi apresentado ao Dr. Marcelo, e que pediu que criássemos a apresentação do Felicilab para o Dr. Cabeto, para que conheça e a gente discuta financiamento.

**Comment by Clarisse1983** [comment]
Conversei sobre essa issue ontem na reunião do grupo tático e ela se mantém, mas sua atualização está condicionada ao planejamento estratégico que iremos realizar na sexta-feira, provavelmente.

**Comment by danielgula** [comment]
Solicitar pauta para apresentar ao Secretário de Saúde a defesa do Prêmio ENAP 2021.
