### ISSUE TITLE
Calendário de efemérides

### ISSUE THREAD

**Issue by Clarisse1983** [EscolaDeSaudePublica/FeliciLab#71]
Com o planejamento dos conteúdos para redes sociais, sentimos a necessidade de ter referências sobre efemérides a serem usadas como base, para gerar discussões e fomentar criações. Temos usado uma referência genérica, mas é importante construir a nossa, com datas e temas que nos sejam relevantes.

Esse conteúdo poderá, inclusive, ser inserido numa agenda em nosso site, informando às pessoas sobre eventos e outras datas significativas.

Referências:
https://www.datascomemorativas.me/2021/abril

**Comment by Clarisse1983** [comment]
Mais uma referência:
https://www.goobec.com.br/blog/datas-especiais-em-2021-para-inspirar-posts-organicos-e-anuncios-no-google-ads-e-faceads/

**Comment by saracafe** [comment]
Algumas referências de datas relacionadas a saúde, ciência e tecnologia: https://docs.google.com/document/d/1OFsHVa-7Hm2diTuyelp_uComEG3YCtkRoGjJOInnFPM/edit?usp=sharing

**Comment by danielgula** [comment]
Em reunião de pauta do Publicilab, precisamos planejar mensalmente essas efemérides, que vão gerar épicos.

**Comment by Clarisse1983** [comment]
Excluindo do git por motivos de "não é uma issue".

**Comment by uira** [comment]
@Clarisse1983 🤣🤣🤣😍❤️
