### ISSUE TITLE
Especial Mulheres na TI

### ISSUE THREAD

**Issue by saracafe** [EscolaDeSaudePublica/FeliciLab#72]
## **Objetivo**

**Como** público externo das redes sociais  
**Quero** saber como as mulheres estão atuando na área de TI  
**Para** me manter informado, fomentar a política de mulher na TI e disseminar conhecimento na área

## **Contexto**

Dia 30/04 é Dia Nacional das Mulheres e está no nosso calendário de publicações no instagram para essa semana. Porém, Claris e eu conversamos e achamos que o assunto é bom e rende um outro olhar sobre o assunto. É essencial ancorar isso na nossa realidade da presença de gênero feminino nas tecnologias da informação. 

Vamos construir a ideia de fazer um especial "Mulheres na TI", serão 5 posts, sempre as terças-feiras, começando dia 18/05.

18/05: a importância das mulheres na TI, falar sobre dados e quantidades, como é a comunidade aqui em Fortaleza e o que o FeliciLab está fazendo para contribuir com isso.

25/05: perfil da Fernanda é nossa primeira personagem. Saber sobre a sua formação, se ela teve dificuldade para entrar na área, a importância das mulheres na TI, e já que ela mora no interior, podemos explorar também essa ideia, se ela tem dificuldade na carreira por conta disso, se é acessível, se ainda existe preconceitos e etc. 

01/06 : perfil da Camila, pode falar sobre a formação, como entrou na área, a importância de se ter mulheres na TI, como é a sensação das pesquisas de dados que ela faz serem divulgadas nacional e internacionalmente, a importância de se trabalhar com dados para a saúde pública

08/06:  perfil da Irlene (chefe do Nutic) falar sobre isso, como as tecnologias mudaram ao longo dos anos, o que isso impacto no trabalho da ESP, a importância de agora sermos uma ICT

15/06: perfil de Helen, ela já trabalha há mais de 15 anos na área. Claris vai entrevistá-la pessoalmente. 

22/06: Análise e fechamento. O que esperamos do mundo e o que o Felicilab está fazendo ou pode fazer para mudar essa realidade

## **PubliciLab**

- [x] Pegar as imagens dos personagens
- [x] Falar com Luis sobre indicação de fontes
- [x] Assistir a um evento gravado no site https://www.igualdadestem.com/ 
- [x] Juntar as informações para fazer o texto da 1º publicação
- [x] Falar com Camila sobre fazer um texto
- [x] Falar com Fernanda sobre fazer um texto, https://docs.google.com/document/d/1PQiAi3B5kLrbw1uuXrQuIAc3duvvYLnmVbv_4TfFpQU/edit?usp=sharing 
- [x] Falar com Irlene (chefe do Nutic) para fazer um texto
- [x] Falar com Helen 
- [x] Fazer um texto de análise deste cenário, o que esperamos nos próximo anos e o que o Felicilab pode fazer para mudar essa realidade

## **DesignLab**

- [x] Propor um conjunto de artes para o blog e o instagram
- [x] Fazer uma arte por episódio com base no contexto

## **Critérios de Aceitação**

- [x] Visualizar conteúdo sobre o especial     
**Dado que** sou uma usuária de redes sociais
**Quando** visito o blog e instagram do felicilab    
**então** eu visualizo e interajo com a publicação

## Observações
Links de apoio e informações adicionais

**Comment by uira** [comment]
@saracafe Ficou muito bom! Principalmente pela pegada de dar visibilidade pro nosso microcosmos.

Vale colocar a Alice, Kelma e Helen, todas atuando com tecnologia, mas vindas de outras áreas.

E podia render uma live final, com todas vocês. 🤩

**Comment by saracafe** [comment]
Para o 1º post: https://docs.google.com/document/d/1CkwgHJ5prcocE5cmWjGDZ2Xp8y7Rk0mbwlj-Gittfjw/edit?usp=sharing

**Comment by Clarisse1983** [comment]
Vamos fazer um episódio extra com a Helen. Ela me pediu hj para participar, e eu acho mais que justo, mil anos na área já. A história dela será o episódio 5 e o fechamento será o seis. @saracafe, por favor crie um card para ela. Vou entrevistá-la amanhã, presencialmente.
