### ISSUE TITLE
Publicação XConf 2020

### ISSUE THREAD

**Issue by saracafe** [EscolaDeSaudePublica/FeliciLab#73]
Texto: https://docs.google.com/document/d/1TeS_Wa97naLzWJ3TGbDyDau-eWP5lWxxQ3WJdHEIIU4/edit?usp=sharing

**Comment by saracafe** [comment]
![Mensagem Roxa de Educação (14)](https://user-images.githubusercontent.com/77791759/116599542-9e8afb00-a8fe-11eb-96f4-58e1fa0a8be1.png)
![Mensagem Roxa de Educação (13)](https://user-images.githubusercontent.com/77791759/116599556-a21e8200-a8fe-11eb-8031-4a9bc2ee1991.png)

**Comment by Clarisse1983** [comment]
Gostei dos 2, mas acho que o roxo orna mais com a arte. E amei a sacada #tbt! É isso aí, parça!!
