### ISSUE TITLE
Especial 'O que é uma ICT'

### ISSUE THREAD

**Issue by Clarisse1983** [EscolaDeSaudePublica/FeliciLab#76]
A ESP se tornou uma ICT e queremos criar um conteúdo informativo sobre isso para nossos cais: o que significa na prática, expectativas de transformação do cenário de inovação na saúde, impactos disso na produção do FeliciLab. Conversar com Rodrigo Silvestre, com Alice Pequeno, pegar umas falas do Dr. Marcelo.

**Comment by Clarisse1983** [comment]
Enviei email para a Ascom sugerindo a pauta e nos colocando à disposição para fazer juntos, e eles responderam apenas agradecendo e dizendo que já iam fazer =/

**Comment by uira** [comment]
@Clarisse1983 vale argumentar que é um assunto técnico e queremos acompanhar e ajudar na revisao.
