### ISSUE TITLE
Alterar cores do logotipo do Cuida para posts no Instagram

### ISSUE THREAD

**Issue by Clarisse1983** [EscolaDeSaudePublica/FeliciLab#79]
## **Objetivo**

**Como** usuária das redes sociais do FeliciLab
**Quero** ver logotipos do Cuida com cores diferenciadas
**Para** ter um indício de que são edições diferentes de postagem

## **Contexto**

- O Júlio, da Ascom, criou um logotipo para o Cuida, que a gente usa como imagem nas postagens no instagram. Mas ele criou com uma única cor de fundo. E como toda semana a gente lança a versão Cuida pro insta, está ficando bem repetitivo usar sempre a mesma imagem, com as mesmas cores. Parece até que o conteúdo é o mesmo.

## **Escopo**

- [x] Fazer novos cards, apenas alterando a cor de fundo do logotipo
Os arquivos estão aqui: https://drive.google.com/drive/folders/1PHFnP1RDjfO8bGKx_BZEdnuHZgqEgzcX

## **Critérios de Aceitação**

- [x] Alterar cores do logotipo 
**Dado que** sou usuária do instagram 
**Quando** visito a página
**então** encontro artes com cores diferentes para cada edição do Cuida

## Observações
Links de apoio e informações adicionais

**Comment by danielgula** [comment]
Os novos arquivos estão no mesmo link para aprovação: 
https://drive.google.com/drive/folders/1PHFnP1RDjfO8bGKx_BZEdnuHZgqEgzcX
