### ISSUE TITLE
Publicação #tbt #felicilab1ano

### ISSUE THREAD

**Issue by saracafe** [EscolaDeSaudePublica/FeliciLab#81]
Quinta é dia de #tbt e #felicilab1ano

Pegar algum fato do roteiro do vídeo de 1 ano do felicilab https://docs.google.com/document/d/13ThM32-vDLcR3-CT8ev-1C2Ylajlu-BpTOuL6aJPa60/edit?usp=sharing

**Comment by saracafe** [comment]
O #tbt de hoje é sobre o MPV do felicilab na primeira Oficina para definição de Estratégias Digitais em Inovação. A ideia foi pegar o mesmo texto que estava no roteiro de vídeo, ajustar dizendo que é tbt e marcar as pessoas. Acho que podemos colocar as próprias fotos mesmo, sem a necessidade de alguma arte https://docs.google.com/document/d/1cMDwIRPOV6FDMNjZa2CcZY3niQVnbMLtJPU6mDOUlJA/edit?usp=sharing

**Comment by Clarisse1983** [comment]
Hoje é dia de #tbt! É vero! Massa, gostei da ideia. Vou só fazer uns ajustes no texto.
