### ISSUE TITLE
[12/05] Criar publicação sobre iSUS

### ISSUE THREAD

**Issue by saracafe** [EscolaDeSaudePublica/FeliciLab#89]
A ascom fez alguns cards e vídeo sobre como se cadastrar no iSUS. Vamos publicar na quarta. 

- Solicitar a ascom esses cards e o vídeo ou fazer o repost

**Comment by Clarisse1983** [comment]
Aqui os cards:
https://drive.google.com/drive/folders/1AGWZ7mAdmonaRO28WpyjrT26Q1J4Eb0W

**Comment by saracafe** [comment]
Aqui o texto: https://docs.google.com/document/d/1tsRd3R-OTc3JDdOCmmosXVWdQMw_QY3s6RaRoo1hdGg/edit?usp=sharing

**Comment by uira** [comment]
@saracafe Gente, fiz um comentário no documento.

Tô achando nossos textos muito grandes pra Instagram... 

Em alguns casos se justifica, mas acho que o padrão tem de ser algo mais sucinto. Inclusive pq a grande maioria das pessoas sequer lê esse texto, o foco é na imagem/vídeo, e só abrem a descrição se estiverem MUITO interessadas. 

Inclusive, é importante q as imagens seja mais instrutivas e provocativas, do que só ilustrativas.
