### ISSUE TITLE
[17/05] Criar post sobre Dia Internacional da Comunicação e das Telecomunicações

### ISSUE THREAD

**Issue by saracafe** [EscolaDeSaudePublica/FeliciLab#93]
Comunicação como direito humano e visão do FeliciLab

**Comment by saracafe** [comment]
Aqui a proposta do texto https://docs.google.com/document/d/1Unk9eh3RMcWLC9D51Aqn1gCEWbZRdasmIWfR-d7sr1s/edit?usp=sharing

**Comment by saracafe** [comment]
@danielgula Claris aprovou esse card. Ficou ótimo. Só é preciso retirar do card o texto dia internacional das comunicações e telecomunicações. Vamos mencionar isso no texto.

**Comment by danielgula** [comment]
![comunicar-direito-humano](https://user-images.githubusercontent.com/39468037/118540543-0fb41600-b727-11eb-8c44-2f3191079ae0.jpg)
Arquivo final

**Comment by Clarisse1983** [comment]
Lindo, @danielgula! Adorei! @saracafe, pode colocar lá na publicação. <3
