### ISSUE TITLE
[18/05] 1º episódio Mulheres na TI

### ISSUE THREAD

**Issue by saracafe** [EscolaDeSaudePublica/FeliciLab#95]
## **Objetivo**

**Como** público externo das redes sociais  
**Quero** saber como as mulheres estão atuando na área 
**Para** saber como está o mercado de estudo, trabalho e oportunidade para as mulheres de STEM

## **Contexto**

Vamos construir a ideia de fazer um especial "Mulheres na TI", serão 5 posts, sempre as terças-feiras, começando dia 18/05. O 1º episódio da série especial irá falar sobre a  importância das mulheres na TI, sobre dados e quantidades, como é a comunidade aqui em Fortaleza e o que o FeliciLab está fazendo para contribuir com isso.

## **PubliciLab**

- [x] Falar com Luis sobre fontes
- [x] Assistir evento gravado no site https://www.igualdadestem.com/
- [x] Pegar depoimento do Luis sobre o assunto ou pegar o contato da professora que estava no evento
- [x] Juntar as informações e montar o texto
- [x] Revisar o texto

## **DesignLab**

- [x] Fazer um layout para essa série especial, com peças para instagram e blog (imagem grande e imagem de destaque)
- [x] Entregar primeira arte até segunda (17/05)

## **Critérios de Aceitação**

- [ ] Visualizar conteúdo sobre o especial
**Dado que** sou uma usuária da internet
**Quando** visito o blog e instagram do felicilab   
**Então** eu visualizo e interajo com a publicação

## Observações
https://docs.google.com/document/d/1CkwgHJ5prcocE5cmWjGDZ2Xp8y7Rk0mbwlj-Gittfjw/edit?usp=sharing

**Comment by pauloamoreira** [comment]
segue layouts para aprovação: card do 1º episódio e padrão para cards dos demais episódios: https://drive.google.com/drive/folders/1w9G72hZNT6w0dADnfiDx4kv_zp4KTXWg?usp=sharing

**Comment by pauloamoreira** [comment]
.segue versão 16:9
![16-9](https://user-images.githubusercontent.com/79201419/118555845-8bb75980-b739-11eb-89f1-b8ab4739d84a.png)
