### ISSUE TITLE
[20/05] Criar publicação de #tbt

### ISSUE THREAD

**Issue by saracafe** [EscolaDeSaudePublica/FeliciLab#97]
Central de Ventiladores

**Comment by saracafe** [comment]
Vídeo de tela entrando no site da central de ventiladores 
https://user-images.githubusercontent.com/77791759/119017123-0cac6600-b971-11eb-8ab6-0dc88a5ff14c.mp4

**Comment by saracafe** [comment]
Aqui o texto: https://docs.google.com/document/d/18ER_MtOqlHKWoaa4PRlsHqGCtMLFyoRPqaiC0NOhnU0/edit?usp=sharing

**Comment by Clarisse1983** [comment]
@saracafe a ideia é exatamente essa, mas pode ficar mais curto, 15 segundos, pra nem precisar ir pro ig tv
