### ISSUE TITLE
[21/05] Criar post sobre Dia Mundial da Diversidade Cultural para o Diálogo e o Desenvolvimento

### ISSUE THREAD

**Issue by saracafe** [EscolaDeSaudePublica/FeliciLab#98]
## **Objetivo**

**Como** público externo das redes sociais  
**Quero** acessar o conteúdo no instagram   
**Para** conhecer o código de conduta do FeliciLab

## **Contexto**

- Dia 21/05 é dia Mundial da Diversidade Cultural para o Diálogo e o Desenvolvimento e como acreditamos que o nosso código de conduta preza pela diversidade, queremos apresentá-lo as pessoas como forma de disseminar essa narrativa. 

## **PubliciLab**

- [x] Analisar o Código de conduta do isus: https://github.com/EscolaDeSaudePublica/isus-app/blob/91e3146c40c3d71a3395340c2c9bbcb210c8ab5c/CODE_OF_CONDUCT.md 
- [x] Analisar a Identidade do Felicilab: https://docs.google.com/document/d/1V_qCI5E1FP5dgfYN9ER5uzT-ZMxBsH33obGWZhYwsvs/edit#
- [x] Exercer o poder de síntese e criar os cards
- [x] Revisar o conteúdo

## **DesignLab**

- [x] Compartilhar o template com barra de logos

## **Critérios de Aceitação**

- [ ] Visualizar conteúdo no instagram  
**Dado que** sou usuária das redes sociais 
**Quando** estou no perfil do FeliciLab  
**então** posso acessar o código de conduta apresentado em cards. 

## Observações
Links de apoio e informações adicionais

**Comment by saracafe** [comment]
@pauloamoreira é possível disponibilizar esse template dos cards para instagram?

**Comment by saracafe** [comment]
Aqui a proposta de texto para os cards https://docs.google.com/document/d/1dIqktYknLauN1_jI0Wn6NqHkNreveBtCMfExigf5K9Q/edit?usp=sharing

**Comment by pauloamoreira** [comment]
@saracafe em que formato devo fazer para ficar mais prático para você editar, inserindo ou alterando a imagem do card quando for necessário? confirmando: você só quer o card vazio (sem imagem) só com a régua de logos, correto? ou precisamos criar a imagem principal desse card?

**Comment by pauloamoreira** [comment]
@saracafe conforme conversamos no telegrama, segue link para grid sem imagem com barra de marcas de publicação para instagram com 1080 x 1080 pixels: https://drive.google.com/file/d/1UyBTsSpQGSJtldkkML7GgkyAk1Tt4aR_/view?usp=sharing este material já está na pasta corresponde no drive do PubliciLab.

**Comment by saracafe** [comment]
Aqui os cards https://drive.google.com/drive/u/0/folders/1ZCXKLbM528O-6759YsgISMXsd1jeGZpZ
